### ISSUE TITLE
Add a "Sync Preferences" button to the account ready page [desktop sync][opened via a new tab] 

### ISSUE THREAD

**Issue by mhammond** [mozilla/fxa-content-server#3079] opened 2015-09-18 01:26 UTC
This is the server-side component of https://bugzilla.mozilla.org/show_bug.cgi?id=1204714. When the user clicks on the "please activate your account" email, we'd like the browser to receive a message after the actual activation so it can take some action (currently that action will be to have the tab switch to Sync prefs)

I've no strong opinion on the message name (but it should probably reflect that it's not a generic "user now verified" message, but instead "user verified via the activation page", which is a subtle distinction) and the message content should include the uid (and probably the email) of the user.

**Comment by rfk** [comment] 2015-09-18 05:03
I recall @ncalexan suggesting they might need something similar for Fennec; Nick, should we triage this into the fennec-web-login milestone?

**Comment by ncalexan** [comment] 2015-09-18 13:39
@rfk yes, Fennec (and Firefox for iOS) would appreciate this.  It's strictly an improvement to our existing behaviour, however, so it's not a day one blocker.

**Comment by ncalexan** [comment] 2015-09-18 13:44
I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1206086 for Fennec.

**Comment by shane-tomlinson** [comment] 2015-09-21 08:20
@ncalexan, @mhammond - I was thinking about an almost identical concept over the weekend to help support #3024 and #3081. For the use case mentioned here, instead of the "user is confirmed via the confirmation page" signal only being sent to other tabs, we'd send it out via the WebChannel as well.

**Comment by mhammond** [comment] 2015-09-21 09:13
Chatting with @shane-tomlinson on IRC, I think we agree that #3024 and #3081 can use the same message we need so long as they don't grow to include the use-case of verification happening in a different browser (in which case a different message would need to be used)

**Comment by ncalexan** [comment] 2015-09-21 17:47
On Mon, Sep 21, 2015 at 2:13 AM, Mark Hammond <notifications@github.com>
wrote:

> Chatting with @shane-tomlinson <https://github.com/shane-tomlinson> on
> IRC, I think we agree that #3024
> <https://github.com/mozilla/fxa-content-server/issues/3024> and #3081
> <https://github.com/mozilla/fxa-content-server/pull/3081> can use the
> same message we need so long as they don't grow to include the use-case of
> verification happening in a different browser (in which case a different
> message would need to be used)
>
Can I get a summary of that chat?

I find this distinction surprising.  The event I want to observe is "the
account transitioned from unverified to verified"; when phrased like that,
it's clearly not important how that came to be.  You could imagine in
future we'll observe that message from Push Notifications; right now, we
might have a WC open to deliver it.  When we do, I want to give the user an
upgraded experience.

**Comment by mhammond** [comment] 2015-09-22 00:45
> Can I get a summary of that chat?
> I find this distinction surprising.

Shane and I were successfully confusing each other, so a copy-paste of the conversation will not help. I think it boils down to:

* For my use-case, I want the message only if the user transitioned to verified via a specific tab in *this browser*.

* A more general use-case is a message when the user transitions to verified, regardless of how or where that happened. It sounds like this is what you are asking for ("it's clearly not important how that came to be.")

For my use-case, we want to take special action on the tab that caused the verification, but take no action on any other tabs that may happen to be on accounts.firefox.com. If the verification happened on a different browser or a different device, no special action should be taken anywhere.

For the more general use-case, imagine the "original browser" has a page on accounts.firefox.com but the user verifies on a different device/browser - the salient question is - does that "original browser" get a message about the verification? IIUC, the implementation being considered is that the verify page itself is what sends the message - so the "original browser" will *not* get the message as that browser never landed on the verify page. However, that smells like an implementation detail and that an obvious future enhancement might be that the "original browser" does get the message - that would then break the flow we are after.

IOW - I'm looking for a message that I know with certainty came from the verification page. That sounds subtly different than a message that indicates the user became verified, even if in the short term the implementation means they are the same in practice.

I hope that makes sense :)

**Comment by shane-tomlinson** [comment] 2015-10-06 20:12
ref #3140 because similar decision logic will be used to decide whether to send this message and whether the sync preferences button can be shown on the verification page.

**Comment by rfk** [comment] 2015-10-30 05:28
There's client-side UX cleanup that's blocked on this work, so I've put it at the top of our "quality" queue for the next train.

**Comment by shane-tomlinson** [comment] 2015-10-30 08:41
> client-side UX cleanup that's blocked on this work

client-side meaning browser, or client-side meaning content-server?

**Comment by shane-tomlinson** [comment] 2015-11-05 13:11
@mhammond and @ncalexan - In #3140, we send a WebChannel message to Fennec after the user clicks a "Sync preferences" button and not automatically. This gives the user an opportunity to see the "You have completed verification" screen and make the choice whether they want to see the `Sync Preferences` pane.

I have implemented similar logic for desktop, where the user clicks the `Sync Preferences` button and desktop opens the correct pane. I actually have the desktop patch (sans tests) working.

![Sync Preferences button->about:preferences#sync](https://irccloud.mozilla.com/file/Z1YzbBtb/open-sync-preferences-from-fxa.gif)

To me it makes sense to use similar modes of interaction for both Fennec and Desktop, meaning I think we should show the button in both environments and give the user the choice.

@mhammond - I can whip the desktop hack I did into shape and open a patch against https://bugzilla.mozilla.org/show_bug.cgi?id=1204714.

**Comment by shane-tomlinson** [comment] 2015-11-05 13:12
@ryanfeeley - could you give your thoughts on the last comment I made, to see if that seems reasonable to you?

**Comment by shane-tomlinson** [comment] 2015-11-05 13:18
@mhammond and @ncalexan - If going with the above scheme where the browser only opens `about:preferences#sync` (or equivalent) once the user clicks the `Sync preferences` button, is a WebChannel message indicating the user has verified still needed, esp w/ the coming push notifications?

**Comment by shane-tomlinson** [comment] 2015-11-05 13:25
@mhammond - FWIU, `context=fx_desktop_v2` is soon going to be a thing, support for the `Sync preferences` button could be a part of that.

**Comment by mhammond** [comment] 2015-11-06 04:45
>  is a WebChannel message indicating the user has verified still needed, esp w/ the coming push notifications?

I think Ryan will need to answer that, but I do think we will need *something*. In the normal flow, the user will now have 2 tabs open (one where they created the account, the other is the link that opened when they clicked on the verify link), so I expect Ryan is going to want some special action taken on one of them.

**Comment by ryanfeeley** [comment] 2015-11-10 15:34
The reason why Fennec and desktop are treated differently is because sync prefs are in a tab on desktop, so we can more naturally take them there. In Fennec, it would be too jarring.

**Comment by shane-tomlinson** [comment] 2015-11-10 16:18
From https://bugzilla.mozilla.org/show_bug.cgi?id=1194537#c7

--------------------

After a chat with Ryan Feeley, I agree with the general goal.

The result of our discussion:

If the user verifies in a 2nd browser with about:accounts open, keep the current behavior and redirect about:accounts to about:preferences#sync. A success message should be shown on about:preferences#sync which is not currently shown.

If the user verifies in the same browser with about:accounts open, the completion tab should redirect to about:preferences#sync where a success message is shown. about:accounts will still show FxA content which will transition to the "You have successfully verified your email" page and a "Sync preferences" button shown. If the user clicks "Sync preferences", the user will be taken to about:preferences#sync.

If the user verifies in the same browser after closing about:accounts, the completion tab should redirect to about:preferences#sync where a success message is shown.

**Comment by rfk** [comment] 2015-11-10 20:56
Sounds good.  Is the concrete thing asked for in this bug (an outgoing message after account activation) the right way to achieve all those flows from our POV?

**Comment by shane-tomlinson** [comment] 2015-11-11 13:45
> Sounds good. Is the concrete thing asked for in this bug (an outgoing message after account activation) the right way to achieve all those flows from our POV?

I think so. It can be a "fire and forget" message. @mhammond - do you want this message sent only if the user signed up using a WebChannel flow, or should the message be sent for the old fx_desktop_v1 broker and the CustomEvent it uses?

**Comment by mhammond** [comment] 2015-11-11 22:14
> do you want this message sent only if the user signed up using a WebChannel flow, or should the message be sent for the old fx_desktop_v1 broker and the CustomEvent it uses?

I think it should only be sent via the webchannel because:

> If the user verifies in the same browser with about:accounts open,

In this scenario we'd get 2 notifications and we'd need some way of ensuring we only take the action once - which we'd probably do by ignoring the CustomEvent completely (as the webchannel message should also give us the browser element the message came from so we can change its URL)

> If the user verifies in the same browser after closing about:accounts,

In this scenario we wouldn't get the CustomEvent as about:accounts is closed.

I guess this means self-hosters et al would not get this fancy behaviour until they upgraded the server, but I think that's OK - this is just minor UX and not key functionality.

**Comment by vladikoff** [comment] 2015-11-30 22:19
@rfk and @vladikoff to talk about this

**Comment by vladikoff** [comment] 2015-12-02 21:49
Hey @mhammond , let's chat about this in Orlando :D

**Comment by shane-tomlinson** [comment] 2015-12-09 15:31
@vladikoff, @mhammond - can you leave your Orlando notes here for posterity?

**Comment by vladikoff** [comment] 2015-12-09 19:45
@shane-tomlinson, basically @ryanfeeley said: ``bring the blue Android "Sync Prefs" button from Fennec to desktop Ready page. ``

It would send the ` SYNC_PREFERENCES: 'fxaccounts:sync_preferences'` to Desktop. this involves a desktop patch. 

https://github.com/mozilla/fxa-content-server/blob/7d8c2c0661c4492895d39cc10ebcbd602f4bf596/app/scripts/models/auth_brokers/fx-fennec-v1.js#L24

cc @mhammond

**Comment by shane-tomlinson** [comment] 2015-12-16 12:04
@mhammond, @vladikoff - has the desktop work been completed for this? If not, I don't mind doing it.

Would this require `fx_desktop_v3` or just pile onto `fx_desktop_v2`?

**Comment by vladikoff** [comment] 2015-12-16 15:52
> @mhammond, @vladikoff - has the desktop work been completed for this? If not, I don't mind doing it.
> Would this require fx_desktop_v3 or just pile onto fx_desktop_v2?

No desktop patch yet. we might be able to pile onto v2 if v2 is only used by nightly.

**Comment by shane-tomlinson** [comment] 2015-12-18 16:55
> No desktop patch yet. we might be able to pile onto v2 if v2 is only used by nightly. 

v2 should already be in Aurora, so we'll have to uplift the functionality to 45 or use an alternative mechanism. We could 1) add a query parameter indicating "opt-in", 2) add a new context, or 3) finally do the capabilities handshake.

**Closed** 2016-01-12 14:23 UTC
Labels: shipit, waffle:review, ❤
