### ISSUE TITLE
If a relier passes in an email parameter, check to see what an account exists for that email before showing a view

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-content-server#1856] opened 2014-11-07 18:56 UTC
If an email exists for that account, show the signin screen, otherwise show the signup screen. 

We don't currently have a clean way to query whether an account exists for an email. We could hack it today by calling `/account/login` with an empty password and see what the error code is (wrong password or unknown email). We could also expose something programmatic to determine if an account exists for an email address, but this would need to be rate limited. Not sure of the priority on this ATM, but it will be useful if we need to migrate another service to FxA that has existing users identified by email address.

**Comment by shane-tomlinson** [comment] 2015-09-08 17:00
ref #3040

**Comment by shane-tomlinson** [comment] 2016-02-08 13:03
Ref #3057

**Comment by shane-tomlinson** [comment] 2016-02-16 18:03
I'm pulling thi out of back log because it relates so closely to #3040 and #3057 which is in progress.

**Comment by rfk** [comment] 2016-02-22 03:50
This appears to be a complete dupe of #3489 so I'm closing it out in favour of that issue, which has more details on concrete implementation.

**Closed by rfk** 2016-02-22 03:50 UTC
Labels: waffle:next
