### ISSUE TITLE
You are now ready to use Firefox Hello link

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2349] opened 2015-04-25 12:22 UTC
![firefox-hello](https://cloud.githubusercontent.com/assets/68213/7332854/0886f864-eb24-11e4-9e34-721cd595c302.png)

When created an account for Hello I noticed that the Firefox Hello does not link to:
https://www.mozilla.org/en-US/firefox/hello/

I think it should because the page even has a blessed button that will open Hello.

**Comment by vladikoff** [comment] 2015-04-25 17:22
By design, see:
https://github.com/mozilla/fxa-content-server/issues/1250
https://github.com/mozilla/fxa-content-server/issues/1942
https://github.com/mozilla/fxa-content-server/issues/1585

**Comment by ryanfeeley** [comment] 2015-04-25 22:08
I'm not sure I understand the rationale yet. It's optional by property. Please don't close this again team!

**Comment by vladikoff** [comment] 2015-04-26 01:07
Yeah, we will be looking at redirects in https://github.com/mozilla/fxa-content-server/issues/2343 as well

**Comment by shane-tomlinson** [comment] 2015-04-26 09:57
> I'm not sure I understand the rationale yet. It's optional by property. Please don't close this again team!

We closed it because Marketplace cannot handle multiple redirects and nobody else was clamoring for it. 

From https://github.com/mozilla/fxa-content-server/issues/1942#issuecomment-66171129

> Let's wait until we integrate with a relier that wants this functionality. Marketplace doesn't, the Loop flow works differently, and signup don't happen on FMD.

and 

> Closing until somebody requests this feature.

**Comment by ryanfeeley** [comment] 2015-04-27 02:12
It was optional by design from the beginning. Hello really needs it. Sync can also benefit.

**Comment by shane-tomlinson** [comment] 2015-04-27 08:17
> It was optional by design from the beginning. Hello really needs it. Sync can also benefit.

Thanks @ryanfeeley - can you provide more detail?

**Comment by ryanfeeley** [comment] 2015-04-27 10:54
From design linked off of sync flow: https://www.dropbox.com/s/oram2kxiv1mv941/Account%20Verified.pdf?dl=0

**Comment by shane-tomlinson** [comment] 2015-04-27 11:50
@ryanfeeley - A few things need fleshed out here.

* The reference to "optional". Does this mean the relier specifies whether they can handle post-verification redirects in more than one tab?
* Where a Sync link goes when clicked.
* Where a Hello link goes when clicked.

**Comment by ryanfeeley** [comment] 2015-04-27 14:36
> The reference to "optional". Does this mean the relier specifies whether 
> they can handle post-verification redirects in more than one tab?

No, I mean that a service can optionally provide a URL. For example, Marketplace may not want to include a link because it won't open in the Marketplace app, but other properties can include a link.

> Where a Sync link goes when clicked.

 https://www.mozilla.org/firefox/hello/

> Where a Hello link goes when clicked.

https://www.mozilla.org/firefox/sync/

It looks like those links forward to the correct locales (in my case, en-US).

**Comment by pdehaan** [comment] 2015-04-27 16:36
CLOSING. WONTFIX

**Comment by vladikoff** [comment] 2015-04-27 16:36
meeting: we need to plan this out

**Comment by ryanfeeley** [comment] 2015-05-11 16:26
Updated with "Proceed" button, removing link from sentence (less options, less confusing) ﻿﻿﻿﻿https://www.dropbox.com/s/oram2kxiv1mv941/Account%20Verified.pdf?dl=0

**Comment by vladikoff** [comment] 2015-08-05 19:28
@rfk what should we do about this?

It would be great to fix this for Hello, but that means it will not work for Marketplace

**Comment by rfk** [comment] 2015-08-10 07:40
> I wish there was a way that we could make "link" behaviour default and make
> Marketplace a special case.

It's probably easier to change Marketplace links than Hello links; would getting Marketplace to include a `verification_redirect=BLAH` flag in their links give us what we need to move forward for other reliers?

**Comment by rfk** [comment] 2015-08-10 07:43
@ryanfeeley let's you and I chat about this and its relative prioritization next time we catch up

**Comment by ryanfeeley** [comment] 2015-08-13 21:05
I'm going to talk with the creative team about replacing the "Account verified" screens with post-verification marketing pages. The current sync marketing page is actually good enough as is to use. Hello not yet, because it doesn't know if you're logged in to Hello.

**Comment by ckarlof** [comment] 2015-08-13 21:08
Related is that I think when you sign in, the tab you use to sign in with auto-closes itself, which has been determined to be confusing. This could also go to said marketed page.

**Comment by rfk** [comment] 2015-08-13 21:08
Just to note, we don't need this for the current cycle, but it may become important again soon as work on Hello ramps up.

**Comment by vladikoff** [comment] 2015-08-31 21:44
@Verdi I noticed in your Invision app demo today you had "You are now ready to use Sync" in the installer but no button to proceed to Firefox. We might want to revisit this feature to make sure we have a nice flow for this case.

cc @ryanfeeley

**Comment by Verdi** [comment] 2015-08-31 21:54
Hi,
Yes - Ryan mentioned this to me. There was actually a text link below the iframe (with wording from a different flow) but, you’re right, a button and better copy is needed. I’ll make sure that get’s in the next version.
Thanks,
Michael
-- 
Michael Verdi • Firefox UX • blog.mozilla.org/verdi <http://blog.mozilla.org/verdi> • irc: verdi

**Comment by shane-tomlinson** [comment] 2015-09-28 16:46
This is very similar to the `Sync preferences` button in #2771.

**Comment by vladikoff** [comment] 2015-11-10 20:58
Closing this until we need links in the Hello flow.

**Closed** 2015-11-10 20:58 UTC
Labels: waffle:backlog
