### ISSUE TITLE
Error state for long email

### ISSUE THREAD

**Issue by udaraweerasinghege** [mozilla/fxa-content-server#5176] opened 2017-06-28 22:43 UTC
When creating an account, if you type in an email that is longer than 64 characters the `create account button` will be greyed out but there is no indication to as why it is an invalid state.

**Comment by shane-tomlinson** [comment] 2017-07-11 16:13
@udaraweerasinghege - 64 characters, or 64 chars on the local side? If 64 chars on the local side, that's by design, as specified in [IETF rfc5321](http://tools.ietf.org/html/rfc5321#section-4.5.3.1.1). See https://github.com/mozilla/fxa-content-server/blob/2ffdc212c03eb9534b53795d3bc25499b8307fc0/app/scripts/lib/validate.js#L28:L41.

**Comment by vladikoff** [comment] 2017-07-11 16:17
`no indication to as why it is an invalid state.`

@udaraweerasinghege can you still repro this? 
![o](https://user-images.githubusercontent.com/128755/28078416-c8defde2-6632-11e7-8126-059979c7f1b8.gif)

I saw it on your machine, but seems like the invalid state is there?

"TWFuIGlzIGRpc3Rpbmd1aXNoZWQsIG5vdCBvbmx5IGJ5IGhpcyByZWFzb24sIGJ1dCBieSB0aGlz IHNpbmd1bGFyIHBhc3Npb24gZnJvbSBvdGhlciBhbmltYWxzLCB3aGljaCBpcyBhIGx1c3Qgb2Yg dGhlIG1pbmQsIHRoYXQgYnkgYSBwZXJzZXZlcmFuY2Ugb2YgZGVsaWdodCBpbiB0aGUgY29udGlu dWVkIGFuZCBpbmRlZmF0aWdhYmxlIGdlbmVyYXRpb24gb2Yga25vd2xlZGdlLCBleGNlZWRzIHRo ZSBzaG9ydCB2ZWhlbWVuY2Ugb2YgYW55IGNhcm5hbCBwbGVhc3VyZS4=@wat.com".length 
372

**Comment by udaraweerasinghege** [comment] 2017-07-11 16:31
Ah I believe we didnt even click the create account button since the form looked disabled with a longer email, so i assumed the form was in an invalid state and the button looked disabled. 

I think this goes with what rfeeley was saying how users think the form is disabled ( I clearly did :p ). I think this issue can be closed. Especially since the button disable looking state will be going away soon.

**Comment by shane-tomlinson** [comment] 2017-07-11 16:56
Thanks for checking @udaraweerasinghege. Closing as "will be fixed by #5130".

**Closed by shane-tomlinson** 2017-07-11 16:56 UTC
Labels: waffle:backlog
