### ISSUE TITLE
Back and Email preferences links are misaligned in smaller viewports

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2499] opened 2015-06-01 21:10 UTC
### Steps to reproduce:
1. Go to https://email.dev.lcip.org/signup and 
2. Verify your account and go to [/settings/communication_preferences](https://email.dev.lcip.org/settings/communication_preferences)
3. Resize your browser narrower.

### Actual results:
![communication_preferences](https://cloud.githubusercontent.com/assets/557895/7923422/bcd0c542-0867-11e5-9da1-1171677105cf.png)
**Figure 1:** Yay!

![communication_preferences](https://cloud.githubusercontent.com/assets/557895/7923428/d040d95a-0867-11e5-8bd5-290de4694c64.png)
**Figure 2:** Not yay.

**Comment by rfk** [comment] 2015-06-01 23:01
I somehow managed to get a session where the mis-alignment stuck regardless of the size of the browser window: https://github.com/mozilla/fxa-content-server/pull/2452#issuecomment-106965139

Haven't been able to reproduce it since

**Comment by rfk** [comment] 2015-06-05 09:16
> I somehow managed to get a session where the mis-alignment stuck
> regardless of the size of the browser window

Aha, I think I was seeing this because my window was too *short*.  Waking it wider didn't make any difference, but making it taller restored the proper alignment.

**Comment by pdehaan** [comment] 2015-06-05 17:00
Yeah, I was looking into this the other day and the media query totally makes sense.
At a certain viewport size, we remove the `float` style, and set `display` to `'block'`. Not sure if we want to disable those rules for this one page or what. But yeah, probably all going to be fixed by @zaach and @johngruen's Settings redesign.

**Comment by shane-tomlinson** [comment] 2015-06-11 13:08
@zaach - is this part of the settings refresh?

**Comment by johngruen** [comment] 2015-06-11 13:10
@shane-tomlinson yep

**Comment by shane-tomlinson** [comment] 2015-07-06 10:42
@johngruen - have you taken care of this in the settings refresh, if not, I'll have @philbooth take a look at it.

**Comment by zaach** [comment] 2015-07-07 18:54
This screen still needs design work for the settings refresh, but the links at the bottom most likely won't remain that way.

@ryanfeeley @johngruen Thoughts on presenting these Comm Pref tasks within the new settings page?

**Comment by ryanfeeley** [comment] 2015-07-07 19:07
Should we start putting the "back" links at the bottom? After the refresh, they'll be done. <img width="479" alt="comm-prefs" src="https://cloud.githubusercontent.com/assets/68213/8554782/a64bdc44-24b9-11e5-9015-9fb0e2f4105e.png">

BTW, I want you to target a train for the refresh @zaach and @johngruen. I don't like us being in this half-state. Let's make the jump and fix! The setting section gets very few views relatively, but the transition state costs the team brain power.

**Comment by zaach** [comment] 2015-07-07 19:41
@ryanfeeley @johngruen How's this:
<img width="640" alt="screen shot 2015-07-07 at 12 31 05 pm" src="https://cloud.githubusercontent.com/assets/3903/8555310/10cf2992-24a4-11e5-9daa-60cd92a2d720.png">

In the closed state, the panel could just say "Change".

**Comment by johngruen** [comment] 2015-07-07 21:22
@zaach: looks good to me...% there should be lines between items, but i can fix that

**Comment by zaach** [comment] 2015-07-07 21:27
Yeah, I live-edited an outdated version. The latest version does have lines.

**Comment by ryanfeeley** [comment] 2015-07-07 21:31
Related: https://github.com/mozilla/fxa-auth-server/issues/972#issuecomment-119345811

**Comment by ryanfeeley** [comment] 2015-07-07 21:49
Looking good! Might tighten the spacing a bit. Would love to see a spinning wheel icon inside the subscribe button (with a disabled cancel) for some user feedback.

**Comment by zaach** [comment] 2015-07-27 21:31
These links are no longer lay'ed out this way in the new settings page. Closing.

**Closed by zaach** 2015-07-27 21:31 UTC
Labels: design, marketing opt-in, settings 2.0, waffle:ready
