### ISSUE TITLE
intern_server tests are exiting silently half way through running tests

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#4816] opened 2017-03-15 21:23 UTC
Which looks like a passing test suite (half run) ;-). This is on the private repo running `* HEAD -> 70023947 -> Release v1.82.1`.

It appears to quit when running tests/server/metrics-unit.js

Running with tests in debugger I see `TypeError: Cannot assign to read only property 'agent' of {"isSampledUser":true}`.

$ node --version
v4.8.0

**Comment by jrgm** [comment] 2017-03-15 22:07
I pulled and built clean on a new ec2, and I can reproduce this (again node v4.8.0). Quits in the same place every time, exit code 0.
```
PASS: metrics-errors - #post /metrics-errors - returns 200 - tags.context () (374ms)
PASS: metrics-errors - #post /metrics-errors - returns 200 - tags.context (settings.avatar.gravatar) (310ms)
PASS: metrics-errors - #post /metrics-errors - returns 200 - tags.context (settings.change-password) (342ms)
PASS: metrics-errors - #post /metrics-errors - returns 200 - tags.context (unknown context) (331ms)
PASS: metrics-errors - #post /metrics-errors - returns 200 - tags.errno () (341ms)
PASS: metrics-errors - #post /metrics-errors - returns 200 - tags.errno (400) (339ms)
PASS: metrics-errors - #post /metrics-errors - returns 200 - tags.errno (Error) (375ms)
0/18 tests failed
PASS: metrics-errors - #post /metrics-errors - returns 400 with invalid body (326ms)
PASS: metrics-errors - #post /metrics-errors - returns 400 with invalid frames (386ms)
0/21 tests failed
PASS: ga metrics - it works with GA (180ms)
PASS: ga metrics - it works with GA path page events (2ms)
PASS: ga metrics - describes _calculateQueueTime (1ms)
PASS: ga metrics - malformed event data (1ms)
0/4 tests failed
PASS: sanity check (52ms)
PASS: process responds with success immediately, calls process.nextTick (10ms)
[fxa-content-server-private]$ echo $?
0
[fxa-content-server-private]$ 
```

**Comment by philbooth** [comment] 2017-03-16 09:57
@jrgm, I couldn't reproduce this locally to try it out, but does the following patch fix the problem?

```
diff --git a/server/lib/routes/post-metrics.js b/server/lib/routes/post-metrics.js
index 26c98a97..2e05d6e5 100644
--- a/server/lib/routes/post-metrics.js
+++ b/server/lib/routes/post-metrics.js
@@ -3,6 +3,8 @@
  * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

 'use strict';
+
+const _ = require('lodash');
 const config = require('../configuration');
 const flowEvent = require('../flow-event');
 const MetricsCollector = require('../metrics-collector-stderr');
@@ -28,7 +30,7 @@ module.exports = function () {
       res.json({ success: true });

       process.nextTick(function () {
-        let metrics = req.body || {};
+        let metrics = req.body ? _.cloneDeep(req.body) : {};

         const contentType = req.get('content-type') || '';
         if (contentType.indexOf('text/plain') === 0) {
```

(I'm assuming it is the assignment to `metrics.agent` on line 45 that throws)

**Comment by philbooth** [comment] 2017-03-16 09:59
> (I'm assuming it is the assignment to `metrics.agent` on line 45 that throws)

(actually line 43 unpatched)

**Comment by jrgm** [comment] 2017-03-16 15:29
So, with that in place, I seem to get past there, but now have an assertion of `expected 'user-agent' to equal 'content-type'`.

**Comment by vladikoff** [comment] 2017-03-17 16:13
This was fixed in https://github.com/mozilla/fxa-content-server-private/pull/24

**Closed by vladikoff** 2017-03-17 16:13 UTC
Labels: waffle:active
