### ISSUE TITLE
Use email codes rather than links for lockbox

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#5990] opened 2018-03-20 02:30 UTC
We've seen several bug reports about the Lockbox flow being confusing, due to the way users need to click through an email link which takes them out of the flow, including https://github.com/mozilla/fxa-content-server/issues/5938 and https://github.com/mozilla/fxa-content-server/issues/5891.

A lot of these issues would disappear if we used codes that you type into the originating window rather than links that open in a new window.  Can we enable the "email-2fa" experiment for all lockbox users in order to help smooth out this flow?

**Comment by vladikoff** [comment] 2018-03-26 16:14
from mtg: "can be done!" but only for login . Need to refocus due to webextension pivot, cc @rfk

**Comment by irrationalagent** [comment] 2018-08-08 21:11
@vbudhram Ryan Gaddis @changecourse was wondering if this was actually a good idea for Lockbox, Ryan can you weigh in on whether Vijay should actually do this? (my apologies if you already hashed this out)

**Comment by changecourse** [comment] 2018-08-08 22:00
@irrationalagent thanks for tagging me.

@vbudhram I don't have a concern with using sign-in codes instead of a link for us as a relier; this will replace the confusion that our users have upon being redirected into the browser (instead of our app) and replace it with some limited friction in having to input the code.

My concern has to do with the specifics of the code itself... based on what I'm seeing in the "Feature Doc: A/B Test sign-in confirmation for reliers" the example shown is an eight character, alphanumeric code, which presents some significant readability barriers (O vs. 0, for instance), and may be security overkill for our purposes... Can we simplify the code to a 6 character, strictly numeric approach, similar to how banks and other institutions confirm sign-in via SMS? 

cc: @davismtl

**Comment by shane-tomlinson** [comment] 2018-08-09 12:16
@changecourse - Thanks for weighing in here, we have a good opportunity to revisit some of the decisions we've made.

As is often the case, there is a balance between usability and security. In general, longer codes that contain characters from large alphabet are considered "more secure" while shorter codes from a small alphabet are considered "more usable". Strict rate limiting and limited lifetimes can allow shorter codes from a reduced alphabet to be "secure enough" in most situations.

Banks using SMS/TOTP are able to use 6-8 character numeric only codes because SMS messages and TOTP applications display the codes nearly instantaneously. Once generated, the codes then have a very limited lifetime, a 6 character numeric TOTP code is generally valid for 30 seconds to 1 minute.

We are under different constraints because email deliverability times vary greatly. We need the lifetime of a code to be on the order of minutes because emails sometimes take longer than expected to appear in a user's inbox. Because the lifetime of the token must be longer, instead of 6 character numeric code, we opted to increase both the code size and alphabet.

We use an alphabet known as [Crockford's base32](https://www.crockford.com/wrmg/base32.html) to provide a sufficient level of security while mitigating some of confusion problems you mention. The alphabet contains the characters `0123456789ABCDEFGHJKMNPQRSTVWXYZ`, O is omitted for the 0/O confusion, the same with I for 1/I. U is omitted so that most English swear words cannot be generated. 

So that's where we are now. Our default position is to start with strong security properties and loosen as needed.

The variables we can play with are:

1. alphabet - currently "Crockford's base 32"
2. code lifetime - currently 1 hour
3. code length - currently 8 characters
4. rate limiting - already pretty strict

From the alphabet, perhaps we can ditch both `0` and `1` to further reduce confusion. Or perhaps we go numeric only, with the caveat that we'd want to make changes elsewhere to offset the reduced security of a smaller alphabet.

For code lifetime, 1 hour does seem excessively long for most circumstances, perhaps 10-15 minutes is sufficient. We have to be careful how low this is set because decreasing the lifetime will increase the number of users who have a bad experience because their email arrives after the code expires.

For code length, we could possibly go down to 6 characters, if we make changes elsewhere to offiset the reduced security of a smaller code.

Rate limiting is where we have the least flexibility because that's already pretty strict.

Maybe there are some simple UX changes we can make w/o drastically reducing the alphabet or changing the code size. Have we tried grouping the characters in the code into two groups of 4? If we drop 0/1, will that mitigate confusion with O/I?

**Comment by vbudhram** [comment] 2018-08-09 14:03
> Can we simplify the code to a 6 character, strictly numeric approach, similar to how banks and other institutions confirm sign-in via SMS?

Unfortunately, I don't believe we would be able to get all those requirements for the reasons @shane-tomlinson mentioned above. However, like he mentioned, there might be a combination of those knobs that we can turn that makes security and usability better.

Something to consider was that A/B test was performed on Sync users which may/may not accurately reflect how a Lockbox user might behave? We could run the experiment with Lockbox users. However, from https://github.com/mozilla/fxa-auth-server/pull/2564, the experiment rules would change a little because we would only request a code *if* the user needs to do a verification. Previously, it would always require a code when the user logged in.

> For code length, we could possibly go down to 6 characters

I would want to lean towards this, if we make the codes last 15mins (pending security approval).

**Comment by changecourse** [comment] 2018-08-09 15:26
@shane-tomlinson thank you for the very comprehensive response! 

Aren't any of the variables involving a code inherently stronger than the email link that exists today? You've provided great context for what levers we can adjust here across these four variables... just trying to understand what the bar of strength and complexity needs to be :) 

Our Lockbox users will be most likely be experiencing this type of flow in a purely mobile context; they will be within the iOS app for auth, receive the email confirmation prompt within our app, and be required to exit our app and switch (most likely) to their mobile email client to retrieve the code. Then they will need to return to the Lockbox app in order to enter this code. 

Since this workflow is handled within a single device, mobile context, and also because we've seen some friction in past usability sessions for someone's ability to easily switch between apps (as the task manager is rarely utilized for quick switching) my biggest concern is "How complex can the code be for someone to remember and enter on their first pass, without copying it or writing it down?"

My gut tells me that there would be two ways to ensure "remembrance" without having to check multiple times:

1. A four digit code, utilizing Crockford's base 32 alphabet
2. A six digit code, utilizing numerals only 
3. A more complex code (either length or alphabet) with an easy ability to copy the code to clipboard (on the email) - Not sure if this is even possible

**Comment by changecourse** [comment] 2018-08-09 15:45
@vbudhram & @shane-tomlinson What I'm getting at with the above comment is this... the previous test documented in that feature doc was done within a desktop-context, where selecting text out of an email, copying it, and pasting it to a browser window is much easier for someone to do, than on mobile.

**Comment by vbudhram** [comment] 2018-08-09 15:49
@changecourse Yea that makes sense.

@moz-jvehent @g-k What are your thoughts on above? Should we setup a security review meeting to revisit the requirements we have for these codes?

**Comment by davismtl** [comment] 2018-08-09 18:45
> was done within a desktop-context, where selecting text out of an email, copying it, and pasting it to a browser window is much easier for someone to do, than on mobile

That is not entirely true. We ran the test on everyone IIRC. Mobile included. @irrationalagent correct me if I am wrong.

Also note that a large proportion of users on desktop (>20%) check their email on their phones and not in another desktop browser tab/window. The context is that most signins are on new browsers and it's just quicker to pull your phone out rather than signing into your email account.

I'd like to say that regardless of the length or complexity of the code, we need to make it easy to copy paste from an email app, even if a button is impossible. We should make sure that it can easily be selected, doesn't wrap, has proper spacing from other email content, a call to action to copy (in case they don't think of it), etc...

**Comment by davismtl** [comment] 2018-08-09 18:51
> The variables we can play with are:
>    alphabet - currently "Crockford's base 32"
>    code lifetime - currently 1 hour
>    code length - currently 8 characters
>    rate limiting - already pretty strict

I would really like to get to 6 characters and see what we can do to gether but I have a feeling the only knob we have to play with is the code lifetime. Crockford's base 32 is already a simplified alphabet and our rate limiting is already strict. :-/

**Comment by g-k** [comment] 2018-08-10 20:04
@vbudhram Feel free to drop a meeting to discuss on our calendars. Julien should be back in a week to ten days.

Thoughts:

* ideally, we could use push notifications for a more secure transport, probably better deliverability and delivery time. Possibly with something like [the autofill feature introduced in iOS 12+](https://developer.apple.com/documentation/security/password_autofill/)

* we can tune the aggressiveness of abuse and fraud detection in addition to the knobs Shane mentions in https://github.com/mozilla/fxa-content-server/issues/5990#issuecomment-411737012

* we could set different lifetimes per email service provider (e.g. "Time to Inbox" from https://status.postmarkapp.com/), but the code complexity might not be worth it

* another alphabet to consider is base56 variant of Base58:

> Compared to Base64, the following similar-looking letters are omitted: 0 (zero), O (capital o), I (capital i) and l (lower case L) as well as the non-alphanumeric characters + (plus) and / (slash).
> A variant, Base56, excludes 1 (one) and o (lowercase o) compared to Base 58.

https://en.wikipedia.org/wiki/Base58 

* if we're trying to make the codes "easy to remember in one pass" (per https://github.com/mozilla/fxa-content-server/issues/5990#issuecomment-411797674), I'd guess the "battery horse stapler" style of longer codes of known words maximizes recall and code complexity (but might reduce code recall by region and locale); six digit codes would be easiest to recognize as a known security flow; and grouping e.g. two four-digit groups might fall somewhere in between. Hard to say without UX tests to verify.

* Not sure what rate limits we have in place or if there are other concerns beyond brute-forcing the codes, but I'd hazard that six digit codes with a fifteen minute lifetime are a reasonable place to start. 

Regardless of the code alphabet, length, and grouping size we end up using, the flexibility to change these parameters will useful in response to an attack (similar to being able to increase work factor for password hashing or negotiate a cipher suite for TLS).

**Comment by vbudhram** [comment] 2018-08-13 15:08
@g-k @changecourse Meeting invite sent!

From [custom-server](https://github.com/mozilla/fxa-customs-server#policies), our current rate limit policy is 10 attempts every 15minutes per account & IP.

* rate-limiting too many attempts to verify randomly-generated codes (config.limits.maxVerifyCodes defaults to 10) have occurred for a given account and IP address, in a given time period (config.limits.rateLimitIntervalSeconds defaults to 15 minutes)

**Comment by linuxwolf** [comment] 2018-08-14 19:37
Just my opinion, and from very simplied calculations ...

I think there's a quick win with reducing the code lifetime.  I'd be curious what led to the current limit; a glance at postmarkapp's stats seems infers the code delivery would be in tens of seconds.  Email is definitely slower than SMS on average, but we're well past the days of tens of minutes to inbox.

If that time is reduced and the current rate limit kept, it would appear that even 6 digit codes would expire before a lot of attack methods would succeed.  An attacker using a distributed network would be more successful, and tightening rate limits for some actions (e.g., code verification) and/or limiting the distinct IPs/account (if possible) would increase the validity time.

**Comment by shane-tomlinson** [comment] 2018-08-14 20:08
>  but we're well past the days of tens of minutes to inbox.

You would *think* so, unfortunately not the entire internet has moved on, I have seen emails show up on Yahoo and Hotmail after several minutes. @philbooth, @irrationalagent do you know if we have any charts on email delivery times, or whether we can even track that?

The rest, spot on. I think we could do go a long way to denying DDOS w/o adding other additional rate limit logic by requiring the token code to be verified from the same IP address as the signin that caused the token to be sent. Sure, some users could flop from Wifi to 4G or vice versa, though I imagine this would be a small minority.

**Comment by linuxwolf** [comment] 2018-08-14 20:36
> You would think so, unfortunately not the entire internet has moved on, I have seen emails show up on Yahoo and Hotmail after several minutes.

Absent real data, I think even the "[sometimes] several minutes" means a 10-15 minute validity period is acceptable, which is unconditionally better than 60 minutes.

Limiting to the same address also seems pretty reasonable for the code-verify case, at least until data contradicts (-:

**Comment by irrationalagent** [comment] 2018-08-14 21:34
we have timestamps for sent and delivered events, so I'll take a look at where things stand

**Comment by irrationalagent** [comment] 2018-08-16 22:04
finally got around to this, this is just data since the beginning of the month:
https://sql.telemetry.mozilla.org/queries/58394/source#151743

Overall the median & 75th percentiles of delivery time (delivered timestamp - sent timestamp) for all domains is < 1 minute. We have to look to the 99.9th percentile for delivery times > 15 minutes. This applies to email domains orange.fr and comcast.net. 

See [this query](https://sql.telemetry.mozilla.org/queries/58489/source) for the number of emails delivered to those domains in the same time-frame. You can estimate how many would have been 15+ minutes (a little more than 1 per 1000 sent).

We would be effectively killing 1 out of every ~1000 flows for those domains if we adopted 15 minute expiration. On the other hand if an email takes that long we are probably at very high risk for an incomplete funnel already (i should probably analyze flow completion rates as a function of delivery time at some point). 

Its still a judgment call but overall given the small numbers of affected flows 15 minutes wouldn't kill us. If we could extend it to 20 we would cover the 99.9th percentiles for all providers with a bit of room to spare.

**Comment by vladikoff** [comment] 2018-08-20 20:57
from mtg: this is blocked on the discussion about the code length

**Comment by rfk** [comment] 2018-09-12 04:06
This is still tagged for train-120, do we intend to make a point-release or should it be bumped?

**Comment by vbudhram** [comment] 2018-09-12 19:28
@rfk I still intend to make a point release for this. Confirmed in slack that Lockbox is good to proceed with enabling only for Mozilla users.

**Comment by shane-tomlinson** [comment] 2018-09-17 12:46
@vbudhram - can this be closed now?

**Comment by vbudhram** [comment] 2018-09-17 13:19
Yea, this has been merged and I tested with Lockbox App 👍🏽

**Closed by vbudhram** 2018-09-17 13:19 UTC
Labels: P2, train-121, waffle:review

**Comment by SorinaFlorean** [comment] 2018-10-24 14:14
Tested with Lockbox app 1.3.1 installed from App Store and following the steps provided by Vijay I can confirm that this is fixed. I received an email "Sign-In code for Firefox" with a code (6 numbers) and I was able to log in to Lockbox app.
