### ISSUE TITLE
running grunt lint locally shows some warnings

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3035] opened 2015-09-07 05:02 UTC
```
bash-3.2$ grunt lint
Running "eslint:grunt" (eslint) task


Running "eslint:app" (eslint) task

app/scripts/lib/metrics.js
  290:9  warning  Expected indentation of 10 space characters but found 8  indent
  291:7  warning  Expected indentation of 8 space characters but found 6   indent

app/scripts/views/mixins/account-locked-mixin.js
  57:9  warning  Expected indentation of 10 space characters but found 8  indent
  63:9  warning  Expected indentation of 10 space characters but found 8  indent
  64:7  warning  Expected indentation of 8 space characters but found 6   indent

✖ 5 problems (0 errors, 5 warnings)


Running "eslint:tests" (eslint) task
```

**Comment by jrgm** [comment] 2015-09-07 05:05
Curiously the git commit hook, shows warnings in scripts/lib, but not in scripts/views.
```
$ git push jrgm fix-version-git-config
Running "newer:eslint" (newer) task

Running "newer:eslint:grunt" (newer) task

Running "eslint:grunt" (eslint) task


Running "newer-postrun:eslint:grunt:1:/Users/jrgm/tmp33/fxa-content-server/node_modules/grunt-newer/.cache" (newer-postrun) task

Running "newer:eslint:app" (newer) task

Running "eslint:app" (eslint) task

app/scripts/lib/metrics.js
  290:9  warning  Expected indentation of 10 space characters but found 8  indent
  291:7  warning  Expected indentation of 8 space characters but found 6   indent

✖ 2 problems (0 errors, 2 warnings)


Running "newer-postrun:eslint:app:2:/Users/jrgm/tmp33/fxa-content-server/node_modules/grunt-newer/.cache" (newer-postrun) task
```

**Comment by TDA** [comment] 2015-09-07 05:55
Tagging @pdehaan as this might be a eslint@1.0 issue.

**Comment by vladikoff** [comment] 2015-09-08 14:43
See https://github.com/mozilla/fxa-content-server/commit/ff1fd47f48cdef076484990d211d294e01e89393#diff-1dc6ee56b778cd91e0327b52aaeaa1b9R5

**Comment by pdehaan** [comment] 2015-09-08 16:11
The `indent` issues are probably due to an **eslint@1.3** regression.
As for the core issue of why the git hook is showing different results than the `grunt lint` task, that sounds like it may be a weird issue w/ **grunt-newer**.

**Comment by pdehaan** [comment] 2015-09-11 22:02
It looks like the ESLint indent issue isn't fixed in **eslint@1.4**, see https://github.com/eslint/eslint/issues/3591#issuecomment-139669222.

**Comment by pdehaan** [comment] 2015-09-21 17:04
ESLint v1.5.0 fixed most/all our indent issues, so hopefully this should be fixed now.
I submitted #3082 which removes all the `HACK:` comments and removed a bunch of `eslint-disable-line` comments.

**Comment by vladikoff** [comment] 2015-09-21 17:11
Yeap no more warnings, thanks Peter!

**Closed by vladikoff** 2015-09-21 17:11 UTC
Labels: waffle:backlog
