### ISSUE TITLE
DesignF not displayed when creating a new account

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6612] opened 2018-10-05 14:32 UTC
Environment:
Stage- Train 122 and Production server (Nightly, Beta, Release)

Steps to reproduce:
1. Go to Menu -> Sign in to sync;
2. Create a new account and type the email;
3. Click the Password field, verify the tooltip displayed.

Expected results: designF is displayed. 
Actual results: designF is not displayed.

![2018_10_05_17_30_04_create_a_firefox_account_to_continue_to_firefox_sync](https://user-images.githubusercontent.com/24588037/46541407-a14b1e00-c8c4-11e8-8922-58ef6af0ee11.png)

**Comment by shane-tomlinson** [comment] 2018-10-05 14:59
designF is only available within the email-first flow. We are slowly getting rid of [the legacy flow](https://github.com/mozilla/fxa-content-server/issues/6125) and don't want to make more work for ourselves by adding new features to a page that's being removed.

**Comment by shane-tomlinson** [comment] 2018-10-31 09:43
Closing as "by design", we may revisit this at some point and can re-open it then. Thanks @SorinaFlorean for noticing this, you aren't the first!

**Closed by shane-tomlinson** 2018-10-31 09:43 UTC
Labels: waffle:backlog
