### ISSUE TITLE
Is this email verification behaviour sane or broken?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#5848] opened 2018-01-23 17:58 UTC
Raised by @ryanfeeley in IRC.

1. User signs up on desktop, does not verify
2. User signs in on mobile
3. User verifies using the first email

Expected result: Both sessions are verified
Actual result: Only the first session is verified

However, the actual result seems like the correct behaviour here to me, hence phrasing this issue as a question. What does everyone else think?

Full transcript:

```
17:01:56 <rfeeley> vbudhram pb I think I found a pretty nasty bug in user testing
17:02:08 <rfeeley> user testing isn't about finding bugs, that's what qa is for
17:02:20 <rfeeley> but anyway if this is true, i'm worried
17:02:27 <rfeeley> 1. Register on desktop in first run, and stay on Choose What to Sync screen. Do not verify. 
17:02:27 <rfeeley> 2. Download and log in on a second device (user was using iOS)
17:02:27 <rfeeley> 3. Check the two emails FxA sent, and click to verify in the older email.
17:02:27 <rfeeley> 4. Desktop becomes connected and auto-advanced to new tab, but second device does not connect.
17:10:30 <rfeeley> It's hard to tell what's going on in the video as the mobile part is done off-screen, but it sounds like this is what happened. There is a happy ending. She just signed in again on mobile, which did not require verification as it was so soon after registration from the same IP.
17:12:34 <pb> rfeeley: okey doke, will open an issue and have a look
17:13:06 <rfeeley> pb thanks! it was a long one to get through and i have 5 more to go through
17:27:35 → b4hand and Seburo joined  
17:36:42 <pb> rfeeley: actually, just going through those steps, it seems like there's good reason to behave that way?
17:38:03 <pb> rfeeley: otherwise it's possible to verify logins from malicious actors when you only wanted to verify a specific login
17:38:12 <pb> (if i've understood your steps right that is)
17:38:36 <rfeeley> i don't think it's a very common flow
17:38:50 <rfeeley> but from what i can tell she registered in desktop
17:38:54 <rfeeley> and then logged in from mobile
17:39:33 <pb> rfeeley: just to check i understand, is your expectation that verifying on one device should verify all unverified sessions for the user?
17:39:34 <rfeeley> on mobile it would send another email and say please verify
17:40:55 <rfeeley> pb that would solve it, but is that an insecure practice?
17:41:34 <rfeeley> she has two devices, both saying "go verify your account".. she does it but only the first device does it.
17:41:47 <pb> rfeeley: yep totally, hence my first comment. what is the behaviour you expect? i don't think i'm following, sorry
17:42:25 <rfeeley> 1. i sign in on desktop but don't verify
17:42:39 <rfeeley> 2. i sign in on mobile and then verify using the first of two emails
17:42:53 <rfeeley> ER - both devices become verified
17:43:04 <rfeeley> AR - only the first device becomes verified
17:43:39 <rfeeley> #1 should be sign up
17:44:48 <pb> rfeeley: ok, understood. seems like the correct behaviour to me, but i'm often wrong. i'll open the issue and we can see what discussion unfolds...
17:45:55 <rfeeley> pb i'll try and test in sync fest tomorrow. this is a tricky one. 
17:46:03 <rfeeley> pb luckily i don't imagine this is common
17:46:34 <rfeeley> the user was just going being a little non-linear in the steps
17:46:53 <rfeeley> our instructions are intentionally vague to discover this kind of thing
17:48:15 <rfeeley> pb we say: Imagine that you have a friend whose technology advice you trust. Your friend tells you about a way to synchronize and back up all of your browsing across of your devices. (1/2)
17:48:31 <rfeeley> The feature your friend recommends is called Sync which is part of the Firefox Nightly you just downloaded. Find where to set up Sync and proceed to set it up with a verifiable email address. If you can't find it, or have already set it up, proceed to the next step. (2/2)
17:48:44 <rfeeley> (spot my typo)
17:51:53 <rfeeley> Then we ask: Firefox Sync requires that you also use it on more than one device to work to its fullest. On a smartphone/tablet of your choosing, please download the Firefox app (not Nightly) and sign in to Sync with the same account. Keep recording and describe what is happening verbally as this is not captured on screen. Once you are signed in to Firefox on
17:51:53 <rfeeley> your smartphone/tablet, proceed to the next step.
```

**Comment by rfk** [comment] 2018-01-23 19:26
This behavior is intentional, for exactly the reason you describe @philbooth - it's a security property of sign-in confirmation.  But maybe we can make it better.

What we want to avoid here, is accidentally verifying sessions that might belong to an attacker from e.g. a password-guessing attack.  So I don't think that a blanket policy of "verifying an unverified account, should verify all sessions for that account" will work.

But I can imagine us doing one or more of the following to improve the situation:

* If you login to an unverified account, we currently send you the "verify your account" email rather than the "confirm this signin" email.  We could reconsider that, and have the login at step (2) send the usual "confirm this signin" email so it's a little more clear what's going on.

* When verifying an account, we could verify all sessions created within X days of account creation.  This would mirror our current rule where we skip sign-in confirmation on new accounts.

* When verifying an account, we could verify all sessions associated with the same IP address.  This would mirror our current rule for IP-profiling to avoid sign-in confirmation, although I suspect it could get messy to implement.

* We could use typed-in codes rather than clicked-on links to help ensure that users don't get off the rails of the preferred flow and get into confusing situations like this in the first place :-)

@ryanfeeley thoughts?

**Comment by vbudhram** [comment] 2018-01-25 17:39
from mtg: Was not able to reproduce this during Syncfest. The desktop session became verified and the ios session got verified.

Moving to backlog, need to test with Android to verify if this happens there.

**Comment by ryanfeeley** [comment] 2018-01-25 18:47
@philbooth yeah, weirdly this worked beautifully in sync fest. i couldn't see what was on the user's mobile screen, but it sounds like this is what was going on.

**Closed** 2018-11-26 17:18 UTC
Labels: question, waffle:backlog
