### ISSUE TITLE
Stretched settings page on short display

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3099] opened 2015-09-25 03:44 UTC
I noticed this while using the web console:

![screen shot 2015-09-24 at 11 06 36](https://cloud.githubusercontent.com/assets/34695/10092593/0ccc6638-62fd-11e5-9ea0-42ec81b0804b.png)

Expected?

**Comment by vladikoff** [comment] 2015-09-25 03:47
Yeah I think that is by design 
cc'ing @johngruen though

**Comment by johngruen** [comment] 2015-09-25 14:36
@vladikoff i honestly don't remember whether this was by design or not, although it might be nicer to specify a reasonable max-width here. Why don't I tinker with this quickly to make a determination once #3089 merges.

**Comment by johngruen** [comment] 2015-10-05 16:09
closed by #3130

**Closed by johngruen** 2015-10-05 16:09 UTC
Labels: waffle:soon
