### ISSUE TITLE
Dead end when you visit force_auth for an email of a deleted account

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-content-server#3057] opened 2015-09-11 19:50 UTC
<img width="535" alt="screenshot 2015-09-11 12 44 51" src="https://cloud.githubusercontent.com/assets/2365255/9824729/953aa3b0-5883-11e5-866c-5df50b7e7c0c.png">

**Comment by shane-tomlinson** [comment] 2015-09-15 16:29
We should at least not cache the account in this case. Possibly allow the user to sign up again, or "use a different account".

@ryanfeeley - thoughts?

**Comment by shane-tomlinson** [comment] 2015-09-15 16:34
If we allow the user to sign in with a different email address, ensure the browser can handle the new address.

**Comment by ckarlof** [comment] 2015-09-15 16:37
This could also be handled by improving how deleted accounts are handled in the browser, which would reduce the likelihood of the user encountering this situation.

However, for when the user does encounter this situation, it would likely be prudent to remove this cached information.

**Comment by ryanfeeley** [comment] 2015-09-15 17:28
Ooh, I would love us to handle deleted accounts better. I thought I opened an issue/bug about this ages ago.

Does this flow make sense:
1. User deletes email
2. Email notification is sent
3. If syncing, the client simply reverts back to original (unauthenticated) state.

Make sense? If so, where to file this cross-repo issue?

**Comment by rfk** [comment] 2015-09-16 01:57
> where to file this cross-repo issue?

ISTM these are several related issues, so let's split them up.

>  2. Email notification is sent

That can go into fxa-auth-mailer and we'll break it down further from there.

>  3. If syncing, the client simply reverts back to original (unauthenticated) state.

I believe we already send notifications to the browser when an account is deleted, or it can discover this through polling, so that one should just show up as a client implementation bug in bugzilla.

Which leaves us with what to do when the user, despite our efforts, lands on the force_auth page with a deleted account.  ISTM that letting them come out of it with an email different to they one they came in with is asking for trouble from a device-behaviour perspective, but maybe we could let them re-create the account from this page?

**Comment by rfk** [comment] 2015-10-30 05:17
This needs @ryanfeeley input to decide on the desired flow and file concrete implementation bugs.

**Comment by ryanfeeley** [comment] 2015-10-30 14:44
I'm more concerned about nipping this in the bud (client) by informing the client about a deleted a device so it can disconnect sync in the client. That way this screen will almost never been seen. To bugzilla?

**Comment by rfk** [comment] 2015-11-05 04:51
> I'm more concerned about nipping this in the bud (client) by informing the client about a deleted
> a device so it can disconnect sync in the client.

Sounds good.  At what point(s) in the client flow should these notifications be sent?

**Comment by vladikoff** [comment] 2015-11-12 22:25
We created a dashboard for https://app.datadoghq.com/dash/80483 to track what errors people get on the force auth page.

**Comment by ryanfeeley** [comment] 2015-11-12 22:28
For accounts that we know have been deleted, we can redirect to a new fixed-username registration page like this: 
![recreate-it](https://cloud.githubusercontent.com/assets/68213/11133258/cc4617bc-8962-11e5-81f7-db17846fe69e.png)

**Comment by rfk** [comment] 2015-11-23 03:57
> For accounts that we know have been deleted

Technically we dont "know" this, because we don't keep a history of deleted email addresses.  But if the user has landed themselves on this force-auth page, and the target address doesn't exist, then it's overwhelmingly likely that their account was deleted.  I think we could show the messaging unconditionally for "account does not exist" errors on this page.

**Comment by ryanfeeley** [comment] 2015-11-23 16:39
@rfk Can't we know it if it's from a cached view of the login page?

**Comment by rfk** [comment] 2015-11-23 21:00
If fxa-content-server was previously interacting with that account and now it's suddenly gone, yes, we can know that.

If your browser sends you directly to accounts.firefox.com/force_auth?email=deleted@example.com, we can't necessarily know whether that account previously existed or not.  But OTOH, there's no reason for anything to direct you to that page unless the account previously existed.

**Comment by ryanfeeley** [comment] 2015-12-02 20:31
Exactly. Let's do it!

**Comment by shane-tomlinson** [comment] 2016-01-18 22:31
Ref #3283

**Comment by shane-tomlinson** [comment] 2016-01-18 22:49
This and #3283 have the same problem, the user deleted the original account (probably on another device) and Fx is asking the user to re-sign in for Sync. In #3283, the user has created another account with the same email address, in this issue they have not.

I have an idea that might fix both issues.

The browser opens the force_auth page with two pieces of information: a `uid` and an `email`. 

On force_auth page load, we can [check whether the `uid` is still valid](https://github.com/mozilla/fxa-content-server/blob/2d7c9e2afe7ad9df0f721ba527615f5b420521ea/app/scripts/lib/fxa-client.js#L105). 

#### `uid` invalid.
* Send a `logout` message to the browser. The browser will have a second or so to disconnect from Sync before the user re-auths, which was a blocker for client-side only solution to #3283. 
* The user can now attempt to sign in. 
* If the email is not registered, the signin endpoint will tell us so and we can do the proposal @ryanfeeley outlined above. Fix for #3057!
* If the email is registered, the user will hopefully be signed in. We get the user's new `uid` from the auth response, send a `login` message to the browser with all of the new information. Fix for #3283!

#### `uid` is valid
* Don't change a thing. Do what we do today.

This is all based on the assumption that the `login` message will arrive after the `logout` message has finished its business.

cc @mhammond - workable?

**Comment by ryanfeeley** [comment] 2016-01-18 22:50
:+1:

**Comment by shane-tomlinson** [comment] 2016-01-19 09:44
@ryanfeeley - another possibility is to wait for the push notifications patch to land in Firefox. When a user disconnects their device or deletes their account, the browser will automatically disconnect from Sync. Users whose browser supports push notifications should no longer be able to get into this state. 

"Do nothing and let a new feature mitigate the problem" seems like a good path forward to me.

I'm not sure how well this will play out in Fennec for Android and iOS- @ncalexan - any input into what will/won't work for our mobile clients?

**Comment by ncalexan** [comment] 2016-01-19 17:55
@shane-tomlinson for Fennec, I wouldn't block anything on quick push notifications uptake.  We're targeting 47 now and even that might slip for hooking up the FxA + background services parts.  For iOS, push notifications are even farther out.

I don't currently watch for a "logout" message from the WebChannel: see https://dxr.mozilla.org/mozilla-central/source/mobile/android/modules/FxAccountsWebChannel.jsm#29 for the messages I recognize.  So that won't (directly) mitigate this.  If you meant "fxaccount:delete_account", that will work, since Fennec doesn't check interact with the user before destroying the account -- we trust the content server to have confirmed intent for us.  See https://dxr.mozilla.org/mozilla-central/source/mobile/android/modules/FxAccountsWebChannel.jsm#322.

**Comment by shane-tomlinson** [comment] 2016-01-20 10:06
Ref #1957, #2019 where the current force_auth dead end behavior was discussed.

**Comment by vladikoff** [comment] 2016-02-08 22:33
blocked by sign in from sign up patch

**Comment by vladikoff** [comment] 2016-02-08 22:33
blocked by sign in from sign up patch

**Comment by vladikoff** [comment] 2016-02-22 22:11
blocked by check email status patch

**Closed** 2016-03-17 19:18 UTC
Labels: waffle:review

**Comment by vladikoff** [comment] 2016-03-17 19:22
WOOT!
