### ISSUE TITLE
OAuth permissions not localized

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/fxa-content-server#6725] opened 2018-11-22 23:28 UTC
Looks like https://github.com/mozilla/fxa-content-server/issues/4758 is back :/ 

![image](https://user-images.githubusercontent.com/1294206/48924249-f7444700-eead-11e8-88ae-69ca747f33ba.png)

**Comment by shane-tomlinson** [comment] 2018-11-23 11:47
Dup of #4758, which we thought was fixed in #6271? Strange.

**Comment by shane-tomlinson** [comment] 2018-11-23 12:14
I can confirm this is borked. :( Thanks @TheoChevalier for letting us know!

**Comment by shane-tomlinson** [comment] 2018-11-23 13:17
I think this is because of the way webpack & babel are converting this module to .es5:

From .es5/views/permissions.js:

> label: (0, _base.t)('Email address'),

Our extraction script looks for `t('string')`

**Closed** 2018-11-26 16:58 UTC
Labels: train-126:qa-needed

**Comment by SorinaFlorean** [comment] 2018-11-29 13:54
We don't test this on stage because we can't point Pocket to use stage, we will test when Train 126 is in production.

**Comment by SorinaFlorean** [comment] 2018-12-07 12:46
We tested this in production in two ways:
- we change the device language to Francais, and we installed Nightly from Play Store and we connect to Pocket and we got only the "Email address (required) not translated. https://i.imgur.com/CXgi7gC.png
- we didn't change the device language but we change the browser language from Settings - General - Language -Francais and we got the same result, "Email address (required) is not translated.

**Comment by SorinaFlorean** [comment] 2018-12-07 12:48
@shane-tomlinson should I open a new issue since the email address is not translated? Based on https://bugzilla.mozilla.org/show_bug.cgi?id=1510310#c16, Train 126 is shipped.

**Comment by shane-tomlinson** [comment] 2018-12-10 16:12
The strings were not correctly extracted for train-126. I'm going to have to ask for a re-check with train-127.
