### ISSUE TITLE
'Download on the App Store' and 'Get it on Google Play' links/icons are missing on iOS and Android devices

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#4817] opened 2017-03-16 22:39 UTC
Migrating from https://github.com/mozilla/fxa-customs-server/issues/187 into the content-server repo; thanks @kkumari22 for filing!

------

Prerequisite: Existing SessionToken
STR:
1.Navigate to 'https://accounts.firefox.com/sms?service=sync'
Note: Tested on iPhone, IPad, Android mobile/tablet

Expected: There should be 'Download on the App Store' and 'Get it on Google Play' link

Actual: 'Download on the App Store' and 'Get it on Google Play' links/icons are missing on iOS and Android devices

![smspage](https://cloud.githubusercontent.com/assets/16670573/24012622/dadd22f6-0a3b-11e7-9676-9d778efc4e5d.png)
![smssentpage](https://cloud.githubusercontent.com/assets/16670573/24012628/e1e27aa6-0a3b-11e7-8613-3f65c35f8124.jpg)

**Comment by vladikoff** [comment] 2017-03-20 20:21
@shane-tomlinson @ryanfeeley could you please confirm that this is by design? (and close it or move the card?)

**Comment by shane-tomlinson** [comment] 2017-03-22 10:46
This is by design, it doesn't really make sense to show "Download Firefox Mobile" when already in Firefox Mobile. See https://github.com/mozilla/fxa-content-server/blob/e1e6a8992568399952cb7baccb59efc24c9ade08/app/scripts/views/marketing_snippet.js#L142.

Closing as "By design". Thanks for the report @kkumari22!

**Closed by shane-tomlinson** 2017-03-22 10:46 UTC

**Comment by ryanfeeley** [comment] 2017-03-22 17:20
@shane-tomlinson Just confirming: we show the app/play store buttons when on mobile, but the SMS is shown on desktop only, correct?

**Comment by shane-tomlinson** [comment] 2017-03-22 21:05
> Just confirming: we show the app/play store buttons when on mobile.

We show the app/play store buttons if in Chrome or Safari on Mobile, NOT Firefox mobile.

> SMS is shown on desktop only

We didn't gate on that. We'll need to add a patch for it.
