### ISSUE TITLE
'grunt eslint' passes; `grunt eslint:tests` fails; break git pre-push hook

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#2714] opened 2015-07-09 01:20 UTC
I had pushed to remote successfully just a moment ago, but after pulling from mozilla/master and picking up "nothing" now my git push fails, complaining about two files I haven't changed. Oddly, `grunt lint` run directly passes with no errors.

Also, `eslint` is complaining about using `self` not `this`, but in this context `self` is an argument to a function, so `eslint` apparently doesn't have a clue what it is whining about.

```
jrgm@ubuntu:~/fxa-content-server$ ./node_modules/.bin/grunt lint
Running "eslint:grunt" (eslint) task


Running "eslint:app" (eslint) task


Running "eslint:tests" (eslint) task


Running "eslint:scripts" (eslint) task


Running "eslint:server" (eslint) task


Running "jsonlint:app" (jsonlint) task
>> 3 files lint free.

Running "jscs:server" (jscs) task
>> 149 files without code style errors.

Running "jscs:app" (jscs) task
>> 271 files without code style errors.

Running "amdcheck:app" (amdcheck) task

Total unused paths: 0 in 0 files.
Total unused dependencies: 0 in 0 files.
Total processed files: 335

Done, without errors.


Execution Time (2015-07-09 01:12:30 UTC)
loading tasks   1.2s  ▇▇▇▇ 8%
eslint:grunt   872ms  ▇▇▇ 5%
eslint:app        6s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 37%
eslint:tests    1.5s  ▇▇▇▇▇ 9%
eslint:server  349ms  ▇▇ 2%
jsonlint:app   502ms  ▇▇ 3%
jscs:server    602ms  ▇▇ 4%
jscs:app        2.4s  ▇▇▇▇▇▇▇ 15%
amdcheck:app    2.7s  ▇▇▇▇▇▇▇▇ 17%
Total 16.2s

jrgm@ubuntu:~/fxa-content-server$ git push jrgm fix-metrics-test-value
Running "newer:eslint" (newer) task

Running "newer:eslint:grunt" (newer) task

Running "eslint:grunt" (eslint) task


Running "newer-postrun:eslint:grunt:1:/home/jrgm/fxa-content-server/node_modules/grunt-newer/.cache" (newer-postrun) task

Running "newer:eslint:app" (newer) task
No newer files to process.

Running "newer:eslint:tests" (newer) task

Running "eslint:tests" (eslint) task

tests/functional/force_auth.js
  23:2  error  Designated alias 'self' is not assigned to 'this'  consistent-this
  32:2  error  Designated alias 'self' is not assigned to 'this'  consistent-this

tests/functional/oauth_force_email.js
  27:2  error  Designated alias 'self' is not assigned to 'this'  consistent-this

✖ 3 problems (3 errors, 0 warnings)

Warning: Task "eslint:tests" failed. Use --force to continue.

Aborted due to warnings.


Execution Time (2015-07-09 01:12:52 UTC)
loading tasks      1.3s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 30%
eslint:grunt      853ms  ▇▇▇▇▇▇▇▇▇ 20%
newer:eslint:app  389ms  ▇▇▇▇▇ 9%
eslint:tests       1.7s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 40%
Total 4.2s


husky - pre-push hook failed (add --no-verify to bypass)

error: failed to push some refs to 'git@github.com:jrgm/fxa-content-server.git'
```

**Comment by pdehaan** [comment] 2015-07-09 01:44
Fixed in #2716 (or at least, it didn't complain to me when I tried pushing that PR).

**Comment by jrgm** [comment] 2015-07-09 02:14
Reduced to this. Why does `grunt eslint` pass, and `grunt newer:estlint` fail. The pre-push hook runs the former.

**Comment by jrgm** [comment] 2015-07-09 02:16
```
jrgm@ubuntu:~/fxa-content-server$ ./node_modules/.bin/grunt eslint
Running "eslint:grunt" (eslint) task


Running "eslint:app" (eslint) task


Running "eslint:tests" (eslint) task


Running "eslint:scripts" (eslint) task


Running "eslint:server" (eslint) task


Done, without errors.


Execution Time (2015-07-09 02:12:30 UTC)
loading tasks   1.2s  ▇▇▇▇▇▇ 12%
eslint:grunt   883ms  ▇▇▇▇▇ 9%
eslint:app        6s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 59%
eslint:tests    1.7s  ▇▇▇▇▇▇▇▇ 17%
eslint:server  441ms  ▇▇▇ 4%
Total 10.3s
```
```
jrgm@ubuntu:~/fxa-content-server$ ./node_modules/.bin/grunt newer:eslint
Running "newer:eslint" (newer) task

Running "newer:eslint:grunt" (newer) task

Running "eslint:grunt" (eslint) task


Running "newer-postrun:eslint:grunt:1:/home/jrgm/fxa-content-server/node_modules/grunt-newer/.cache" (newer-postrun) task

Running "newer:eslint:app" (newer) task
No newer files to process.

Running "newer:eslint:tests" (newer) task

Running "eslint:tests" (eslint) task

tests/functional/force_auth.js
  23:2  error  Designated alias 'self' is not assigned to 'this'  consistent-this
  32:2  error  Designated alias 'self' is not assigned to 'this'  consistent-this

tests/functional/oauth_force_email.js
  27:2  error  Designated alias 'self' is not assigned to 'this'  consistent-this

✖ 3 problems (3 errors, 0 warnings)

Warning: Task "eslint:tests" failed. Use --force to continue.

Aborted due to warnings.


Execution Time (2015-07-09 02:12:48 UTC)
loading tasks      1.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇ 29%
eslint:grunt      910ms  ▇▇▇▇▇▇▇▇▇▇ 21%
newer:eslint:app  369ms  ▇▇▇▇ 9%
eslint:tests       1.7s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 40%
Total 4.2s

jrgm@ubuntu:~/fxa-content-server$
```

**Comment by jrgm** [comment] 2015-07-09 02:33
So, `./node_modules/.bin/grunt eslint` passes but `./node_modules/.bin/grunt eslint:tests` fails, despite `grunt estlint` claiming to run `grunt eslint:tests`.

**Comment by jrgm** [comment] 2015-07-09 02:43
Reproduced https://github.com/mozilla/fxa-content-server/issues/2714#issuecomment-119791823 on a clean `git clone fxa-content-server; npm install; ./node_modules/.bin/grunt eslint && ./node_modules/.bin/grunt eslint:tests`

**Comment by jrgm** [comment] 2015-07-09 02:51
So I did `npm install eslint`. And `./node_modules/.bin/eslint ./tests` fails with the those bogus errors showing. So two bugs: 1. grunt eslint is not telling the truth, and 2. ./node_modules/.bin/eslint's consistent-this rule is broken.

Given that consistent-this is broken, and had dubious value to begin with it should just be removed. Leaving this bug as #1 `grunt eslint` is not reporting what `eslint` alone reports.

**Comment by TDA** [comment] 2015-07-09 03:59
@saipc reporting in for service! Has this been fixed or am I the only one not getting errors? @pdehaan

**Comment by vladikoff** [comment] 2015-07-09 15:23
> That would solve our problems permanently instead of having to wait for the ESLint team.

That would not solve our problems permanently because the eslint task is not working correctly.

**Comment by TDA** [comment] 2015-07-09 16:22
@vladikoff But it will for this particular instance, and we wont have to wait till that bug is fixed by ESLint. its better than adding an ignore directive, imo.

**Comment by vladikoff** [comment] 2015-07-09 16:29
to reproduce easily:
`grunt eslint` passes
`grunt eslint:tests` failes

**Comment by TDA** [comment] 2015-07-09 16:39
Looking at the logs for both the scenarios, 
https://pastebin.mozilla.org/8839074 - grunt eslint -v
https://pastebin.mozilla.org/8839075 - grunt eslint:tests -v

They seem to run on the same set of files for the test/ directory. This is either a configuration problem or a ESLint issue. Since @vladikoff says it changes behaviour once we shift the order of the tests, it might be just a config issue.

**Comment by vladikoff** [comment] 2015-07-09 16:41
@TDA so we do need fix the warnings itself, should the warnings be there? 

we need `grunt eslint:tests` passing on its own first. otherwise I'm looking into eslint code at the moment

**Comment by vladikoff** [comment] 2015-07-09 16:54
comparing the rules running in the node eslint module, I get this one diff:
![image](https://cloud.githubusercontent.com/assets/128755/8601368/aa54f18c-2639-11e5-8536-58b7fcbec805.png)

**Comment by pdehaan** [comment] 2015-07-09 17:06
Also see https://github.com/eslint/eslint/issues/1846

Still not sure what the best answer here is:

1. Disable the `consistent-this` rule for this repo.
2. Ignore the `consistent-this` rule for those 3 `self` function arguments.
3. Rename the 3 `self` function arguments to something else so it doesn't do a mid-air collision with `consistent-this`.

**Comment by vladikoff** [comment] 2015-07-09 17:07
Files eslint bug here: https://github.com/eslint/eslint/issues/2961

**Comment by vladikoff** [comment] 2015-07-09 17:08
> Rename the 3 self function arguments to something else so it doesn't do a mid-air collision with consistent-this.

This sounds good.

**Comment by TDA** [comment] 2015-07-09 18:31
@vladikoff Now that the bugs been considered legit by the eslint team, I would say we rename the args to {'me', 'that' or 'context'} instead of 'self' (we use all three in the other repos). Can I go ahead with this?

**Comment by vladikoff** [comment] 2015-07-09 18:32
> @vladikoff Now that the bugs been considered legit by the eslint team, I would say we rename the args to {'me', 'that' or 'context'} instead of 'self' (we use all three in the other repos). Can I go ahead with this?

:+1:

**Closed** 2015-07-09 19:08 UTC
Labels: waffle:needs review
