### ISSUE TITLE
Verification email not received when log in with an account with TOTP enabled

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6070] opened 2018-04-16 13:11 UTC
Prerequisite: use an account with 2FA enabled.

STR:

1. Sign In with an account with unverified session.
2. Paste the security code provided by app.
3. Tap on Verify and pay attention to the next page.

Actual results: "This Firefox is connected" page is displayed and the user is successfully signed in. 
Expected results: An email to confirm your new sign-in to Firefox is sent.

**Comment by shane-tomlinson** [comment] 2018-04-16 14:42
@SorinaFlorean - Are you expecting an email that says "A new firefox is connected" or the email that makes you click a link/copy a code?

**Comment by SorinaFlorean** [comment] 2018-04-16 15:18
Sorry for not make myself clear, I expect an email for verifying an existing account (wasn't used for some time).

**Comment by vladikoff** [comment] 2018-04-16 16:12
@vbudhram can you confirm what this should?

**Comment by vladikoff** [comment] 2018-04-16 16:12
should do*

**Comment by rfk** [comment] 2018-04-24 23:36
> Actual results: "This Firefox is connected" page is displayed and the user is successfully signed in.
> Expected results: An email to confirm your new sign-in to Firefox is sent.

IIUC this is all working as intended.  The TOTP verification code is used instead of the sign-in confirmation email, so the actual result here is the correct one - after entering a valid TOTP code your Firefox is connected to sync and no further action is required.

I'm going to close this as working as intended; @vbudhram please re-open if that's not accurate, or @SorinaFlorean please re-open if that doesn't sound right to you.

**Closed by rfk** 2018-04-24 23:36 UTC
Labels: waffle:backlog
