### ISSUE TITLE
Login form does not submit unless credentials are edited

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3387] opened 2016-01-14 22:07 UTC
I tried to log in with Safari, but my password was not accepted.
I reset my password in Firefox to the one that was not being accepted in Safari.
I went back to Safari and pressed **Sign in** and because the form had not been changed, it would not accept the credentials.

<img width="508" alt="screenshot 2016-01-14 17 04 53" src="https://cloud.githubusercontent.com/assets/68213/12339049/f7f2de18-bae0-11e5-9d43-0d85fccab40d.png">

**Comment by shane-tomlinson** [comment] 2016-01-15 11:50
@ryanfeeley - this is by design to minimize the number of requests made to the server, intentionally preventing users from submitting over and over again with the same input. The case you outlined here seems like a real edge case that shouldn't be optimized for.

**Comment by ryanfeeley** [comment] 2016-01-15 15:19
@shane-tomlinson Can we be sure it's an edge case? Are there any metrics collected for this event? We definitely have metrics that support that password resets are very common, and often performed on different devices. I don't think it's uncommon that people use a previous password when doing a reset (it's probably what's in their password manager).

I'm concerned that we're locking the login screen in this state indefinitely and giving the user no feedback. The screen is essentially under glass and they don't know it.

If the concern is server load, I think a timer would be fine. A reset takes a minute probably. How many seconds would be acceptable?

**Comment by shane-tomlinson** [comment] 2016-01-19 17:59
> If the concern is server load, I think a timer would be fine. A reset takes a minute probably. How many seconds would be acceptable?

I think that could work. We should measure whether the account locked rate changes.

**Comment by vladikoff** [comment] 2016-04-13 17:50
To sum up the discussion:

- change the behaviour from `character change` to a `timer + character change`
- measure if account locked rate spikes.

**Comment by vladikoff** [comment] 2016-04-22 19:30
@larissagaulia this is a good bug to investigate if you have time

**Comment by larissagaulia** [comment] 2016-07-04 21:02
@ryanfeeley, what do you mean by ["A reset takes a minute probably. How many seconds would be acceptable?"](https://github.com/mozilla/fxa-content-server/issues/3387#issuecomment-171989171) ? I guessed we could use 1 minute, but @vladikoff thinks it's too long.

**Comment by vladikoff** [comment] 2016-07-04 21:05
Here's 2 seconds:

![type](https://cloud.githubusercontent.com/assets/128755/16569833/68ce8e34-4209-11e6-895e-ca7e9d84fe10.gif)


@ryanfeeley if we extend the timer, do you want the error message to go away or stay?

**Comment by larissagaulia** [comment] 2016-07-04 21:09
Taking the user case from the [example](https://github.com/mozilla/fxa-content-server/issues/3387#issue-126759475), I would find it weird to have both "incorrect pwd" panel and signin button enabled...

**Comment by vladikoff** [comment] 2016-07-05 16:25
cc @ryanfeeley

**Comment by ryanfeeley** [comment] 2016-07-05 17:40
For the sake of manageability, I'm trying to reduce the complexity of our UI.

Now that we have a proper disabled button, I think we don't need to do anything special in this case. The user can see that they need to edit the credentials (even if just removing and readding the same character) before they can submit again.

Let's not worry about timers.

@vladikoff @shane-tomlinson

**Comment by vladikoff** [comment] 2016-07-05 18:51
Okay closing this if we don't need a timer, let me know if I got confused.

**Closed by vladikoff** 2016-07-05 18:51 UTC
Labels: ux, waffle:review
