### ISSUE TITLE
Are signinCodes working correctly on iOS?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#5454] opened 2017-09-08 09:46 UTC
Here is a [chart showing `signinCode` consumption broken down by platform](https://sql.telemetry.mozilla.org/queries/32397#86165):

<img width="637" alt="Screenshot of a chart showing vastly more signinCodes being consumed on Android than on iOS" src="https://user-images.githubusercontent.com/64367/30205808-e8fa2912-9481-11e7-93ae-ab4a0c863a65.png" />

At first glance, that seems like an extremely small proportion of iOS devices.

But then here is a [chart showing general `/signin` views on Android vs iOS](https://sql.telemetry.mozilla.org/queries/32399#86169):

<img width="634" alt="Screenshot of a chart showing vastly more general sign-in views on Android than on iOS" src="https://user-images.githubusercontent.com/64367/30205960-80988656-9482-11e7-9db3-7009b2334de6.png" />

Which seems to suggest that the proportion in the first chart may be about right after all. So I think this is fine, but wanted to record it somewhere in case it isn't fine and also to give anyone else a change to dig deeper if they feel so inclined.

**Comment by philbooth** [comment] 2017-09-08 09:50
/cc @shane-tomlinson @vbudhram @davismtl

(is Leif on GitHub btw? tried @-ing him too but couldn't find him in the dropdown)

**Comment by vbudhram** [comment] 2017-09-12 21:05
iOS 8.3 was recently landed with fixes to https://github.com/mozilla/fxa-bugzilla-mirror/issues/346 and https://github.com/mozilla/fxa-bugzilla-mirror/issues/354. I verified that these [instructions](https://github.com/mozilla/fxa/blob/9dfea8e69da0675d33fe3e94fe29d90f3b26de57/features/FxA-54-connect-another-device-phase-3/README.md#ios) work as expected, even when delaying going through onboarding flow.

After refreshing graph, the metrics above have not really changed. Would there be something at play here?

**Comment by davismtl** [comment] 2017-09-12 22:40
IIUC signinCode is the token used to pre-populate the email?

If that is correct, then I feel like something is wrong on iOS because we noticed a clear spike on Android (consumption and form_views). I'd expect a similar spike on iOS if everything is behaving as intended.

**Comment by davismtl** [comment] 2017-09-12 22:46
IIUC signinCode is the token used to pre-populate the email?

If that is correct, then I feel like something is wrong on iOS because we noticed a clear spike on Android (consumption and form_views). I'd expect a similar spike on iOS if everything is behaving as intended.

CC @irrationalagent

**Comment by davismtl** [comment] 2017-09-13 20:41
from meeting with @philbooth and @irrationalagent 

- We should see an uptake in signinCodes being consumed on iOS since Sept 7th thanks to a patch that @vbudhram landed but for now there seems to be no change.
- Also, based on the volume, the changes in form view and signinCodes should be unrelated. We aren't even sending enough people through the A/B test to come close to accounting for the increase in form views on Android.
- Which leads me to... what's causing the increase in form views on Android?

**Comment by vladikoff** [comment] 2017-09-18 20:47
In progress!

**Comment by irrationalagent** [comment] 2017-09-19 17:49
Quick update: I took a first look at the proportion of sign-in codes that are eventually consumed, and it looks somewhat low (less than 10%): 
![screenshot-2017-9-19 fxa signin codes used as proportion of codes sent](https://user-images.githubusercontent.com/5625313/30606859-f358aaf6-9d27-11e7-8251-a126eacfb977.png)

see https://sql.telemetry.mozilla.org/queries/39209#105375

next step is to break these proportions down by device, to see if its substantially lower on one platform over another

**Comment by vladikoff** [comment] 2017-10-02 21:06
from mtg: @irrationalagent anything else we can do here?

**Comment by vbudhram** [comment] 2017-10-02 21:06
Ref https://github.com/mozilla/fxa-bugzilla-mirror/issues/379

**Comment by davismtl** [comment] 2017-10-02 21:13
@vbudhram and @vladikoff 
My belief is that there is a bug on ios. @irrationalagent mentions that about 7-14% of codes are being consumed.
Meanwhile, on Android consumption is like 90%.

**Comment by rfk** [comment] 2017-10-03 01:55
The answer to the question in this bug's title is clearly "no", and IIUC mozilla/fxa-bugzilla-mirror#379 is about figuring out the problem and fixing it.  Do we need to do any further analysis of the metrics here, or should we close it in favour of that implementation bug?

**Comment by vbudhram** [comment] 2017-10-03 13:58
> we close it in favour of that implementation bug?

I am in favor that. 

For completeness, here is a [query](https://sql.telemetry.mozilla.org/queries/46974/source) that shows a breakdown of consumed codes on iOS devices (ua, browser, version). It shows that iOS versions 8.1, 8.1.1, 9.0 and 9.1 have consumed codes. It also showed that there was a code consumed on Mac back in July and none after, maybe it was testing related? This probably reduces the chance that users received text message on Mac through iMessage and clicked the link.

iOS versions < 9.1 suffered from https://github.com/mozilla/fxa-bugzilla-mirror/issues/354 which *should* have been fixed in https://github.com/mozilla-mobile/firefox-ios/pull/3020. This fix might not be working as intended or is incomplete.

**Comment by rfk** [comment] 2017-10-16 04:17
Closing this in favour of mozilla/fxa-bugzilla-mirror#379

**Closed by rfk** 2017-10-16 04:17 UTC
Labels: train-98, waffle:active
