### ISSUE TITLE
Removed secondary email can't be re-used to create an account

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla/fxa-content-server#6427] opened 2018-08-10 12:29 UTC
Build: Production - Firefox 61.0.2

STR:
1. Create an account.
2. Add a secondary email and confirm.
3. Change the secondary email to be the primary.
4. Remove the secondary email and disconnect.
5. Create a new account with the same email address.

Expected results:
The email that was removed should be re-usable in case the person needs a second account.

Actual results:
The email removed can't be re-used: "Primary account email required for sign-in."

Note: Can create an account with the removed secondary email address if it was not a primary email before.

**Comment by vbudhram** [comment] 2018-08-10 13:33
@sv-ohorvath Thanks for report! This is a duplicate of https://github.com/mozilla/fxa-auth-server/issues/2102.

**Closed by vbudhram** 2018-08-10 13:33 UTC
