### ISSUE TITLE
[train99,stage] consistent test failure for [can change primary email, reset password and login] Error: EmailTimeout

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#5678] opened 2017-11-01 23:45 UTC
Is there some configuration change that is needed in stage? Also, is it really calling timeout in 10 seconds (although probably unlikely why this is failing)?

```
[23:28:38][firefox on any platform] settings change email (2m:12s)
[23:28:54][settings change email] does no show change email option if query `canChangeEmail` not set (5s)
[23:29:14][settings change email] can change primary email and login (8s)
[23:29:39][settings change email] can change primary email, change password and login (11s)
[23:30:08][settings change email] can change primary email, reset password and login (14s)
[23:30:15][Step 1/1] Waiting for email at: http://restmail.net/mail/signin0.23223897842980312
[23:30:16][Step 1/1] Waiting for email at: http://restmail.net/mail/signin0.23223897842980312
[23:30:18][Step 1/1] Waiting for email at: http://restmail.net/mail/signin0.23223897842980312
[23:30:19][Step 1/1] Waiting for email at: http://restmail.net/mail/signin0.23223897842980312
[23:30:20][Step 1/1] Waiting for email at: http://restmail.net/mail/signin0.23223897842980312
[23:30:21][Step 1/1] Waiting for email at: http://restmail.net/mail/signin0.23223897842980312
[23:30:22][Step 1/1] Waiting for email at: http://restmail.net/mail/signin0.23223897842980312
[23:30:23]
[can change primary email, reset password and login] Error: EmailTimeout
  at <tests/lib/restmail.js:53:35>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:593:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:56:25>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:715:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:56:25>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:732:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:56:25>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:843:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:56:25>
  at Test.can change primary email, reset password and login [as test]  <tests/functional/settings_change_email.js:147:10>
```

**Comment by vbudhram** [comment] 2017-11-02 02:58
@jrgm Ah ha, I think I know what the issue is. 

All our circle tests run against the latest auth-server (master contains an extra email when user changes primary email). When I did https://github.com/mozilla/fxa-content-server/pull/5676 (v99.1) all test were green because it accounted for extra email.

Auth-server train-99 does not send the extra email which cause content-server train 99.1 to timeout waiting for it.

I am not sure what the best practice here would be but I can open a PR to revert https://github.com/mozilla/fxa-content-server/pull/5676 and do another point release for it (circle tests will fail since they point to master auth-server).

Maybe this can be another reason to move to a mono-repo 😃

**Comment by vbudhram** [comment] 2017-11-02 03:09
FWIW, content-server 99.0 and auth-server 99.0 play nicely together if you didn't want to hold up trains for test fixes.

**Comment by vladikoff** [comment] 2017-11-02 16:49
See this event that can help with this: https://github.com/mozilla/fxa-auth-server/blob/master/bin/key_server.js#L165

**Comment by vbudhram** [comment] 2017-11-10 15:56
This was fixed in https://github.com/mozilla/fxa-auth-server/commit/98b1d15c794f7b37b5067c190032a04cadac4ca9

**Closed by vbudhram** 2017-11-10 15:56 UTC
Labels: waffle:active
