### ISSUE TITLE
Session expired sign in loop

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#1964] opened 2014-12-09 17:39 UTC
STEPS:
1. I was getting a "Sync has been unable to sync for 14 days" message.
2. I clicked Preferences and then Manage
3. I was signed into the web as a different account, so I signed out of that
4. I was then shown this screen, and when I pressed sign in, it was stuck in a loop.

![expired](https://cloud.githubusercontent.com/assets/68213/5362314/2d4225ba-7fa0-11e4-9e2f-05a6bc88a5ce.gif)

DESIRED RESULTS:
1. When I click Manage in Sync prefs, it should only go to the account I'm syncing with
2. This state should have revealed the password field instead of showing that error

**Comment by vladikoff** [comment] 2015-02-02 04:04
@zaach should we close this?

**Comment by zaach** [comment] 2015-02-02 04:12
No, this hasn't been fixed AFAICT.

**Comment by vladikoff** [comment] 2015-08-25 18:11
@shane-tomlinson @ckarlof if you have time could you check if this still happens, I tried following the steps to reproduce but now I always get a password input and it seems to be working.

**Comment by ckarlof** [comment] 2015-09-11 19:58
I couldn't repro the steps here: https://github.com/mozilla/fxa-content-server/issues/1964#issuecomment-67322664

I did get a strange screen with a missing default avatar, though. I'm closing this as WORKSFORME.

<img width="521" alt="screenshot 2015-09-11 12 54 34" src="https://cloud.githubusercontent.com/assets/2365255/9824878/b2bee63e-5884-11e5-916e-f3536c39c4d0.png">

**Closed by ckarlof** 2015-09-11 19:58 UTC
Labels: waffle:backlog
