### ISSUE TITLE
[iOS, Android] Disable button from Two-step authentication section is not responsive

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa-content-server#6687] opened 2018-11-05 16:08 UTC
Environment: Stage server - Train 124
Prerequisites: Make sure you are logged with an IOS device and have the ''two-steps authentification'' enabled.

Steps to reproduce:
1.  Go to manage account;
2.  Tap on ''Change'' button from Two-step authentification;
3. Tap on "Disable";

Expected results:
Two-step authentication is disabled.

Actual results:
Two-step authentication is not disabled.

Note: 
It's reproducible also if 2FA is enabled from Desktop/Android.

Here is a video with the problem : [link](https://drive.google.com/file/d/1p5BrrbcvTJmeoUzuZKxqPlCg8lsVwnCL/view?usp=sharing)

**Comment by SorinaFlorean** [comment] 2018-11-16 13:04
Reproducible also on HTC 10(Android 8.0) - Stage Train 125.

**Comment by shane-tomlinson** [comment] 2018-12-17 15:50
@SorinaFlorean, @sv-sdeiac - I wonder if this could have been due to [a problem we fixed last week w/ being able to view settings after password reset w/ TOTP enabled](https://github.com/mozilla/fxa-auth-server/pull/2781/commits/3f73c68f4305550e7c99bcb605e714bca8d4589e)? Can you re-test this to see if it still occurs?

**Comment by SorinaFlorean** [comment] 2018-12-17 16:13
I saw this issue today on Android 7.1.1, but now I can't reproduce it, on the same device and on iOS is working as well. My guess is that is not reproducible 100%.  Tested also on production and I couldn't reproduce it.

**Comment by shane-tomlinson** [comment] 2018-12-17 16:18
> My guess is that is not reproducible 100%.

The plot thickens. Thanks @SorinaFlorean for checking!

**Comment by vladikoff** [comment] 2019-01-11 14:54
This feels like the unverified session bug

**Comment by shane-tomlinson** [comment] 2019-01-22 17:48
Closing as a dup of #6767

**Closed by shane-tomlinson** 2019-01-22 17:48 UTC
Labels: waffle:next
