### ISSUE TITLE
Server is not loading in latest Nightly

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#5114] opened 2017-06-01 02:13 UTC
![](http://v14d.com/i/592f77b88d2f2.jpg)

Same on latest: 

![image](https://cloud.githubusercontent.com/assets/128755/26661853/30a2457e-464e-11e7-91b5-f6ff1fd164c0.png)

Prod works, so maybe something with latest commits

**Comment by rfk** [comment] 2017-06-01 02:14
Happens for me as well FWIW

**Comment by rfk** [comment] 2017-06-01 02:15
It loads fine for me in release Firefox though; my first thought is some interaction with the new device-handshake work that @shane-tomlinson landed recently.

**Comment by vladikoff** [comment] 2017-06-01 02:17
Caused by https://github.com/mozilla/fxa-content-server/pull/4695

**Comment by vladikoff** [comment] 2017-06-01 02:19
This should probably block train-88 deploy

**Comment by rfk** [comment] 2017-06-01 02:21
Hmm...so I wonder if this is caused by our dev environments not being in the webchannel allowlist in firefox. If you reconfigure Firefox to point to nightly.dev.lcip.org rather than just loading it in a tab, does the issue go away?

**Comment by rfk** [comment] 2017-06-01 02:21
(Also if this is the case, I would expect softvision to find the same issue on stage)

**Comment by rfk** [comment] 2017-06-01 02:22
Which...yep, I see this same behaviour when opening https://accounts.stage.mozaws.net/ on Nightly.

**Comment by vladikoff** [comment] 2017-06-01 02:23
> Hmm...so I wonder if this is caused by our dev environments not being in the webchannel allowlist in firefox. If you reconfigure Firefox to point to nightly.dev.lcip.org rather than just loading it in a tab, does the issue go away?

Yes goes away. Tested with 

```
FXA_ENV=latest FIREFOX_BIN=/Applications/FirefoxNightly.app/Contents/MacOS/firefox npm start

> fxa-dev-launcher@1.0.0 start /Users/vladikoff/mozilla/fxa-dev-launcher
```

**Comment by rfk** [comment] 2017-06-01 02:24
OK cool, at least we have a working theory :-)

I think we should (a) back out that PR, assuming we can do so cleanly, and then (b) figure out how to make that webchannel handshake fail gracefully when the site is not on the webchannel allowlist in Firefox.

**Comment by shane-tomlinson** [comment] 2017-06-01 09:42
I don't think we should back out the PR, I think we should fix the problem. If there's a browser misconfiguration for the environment and we receive a "No Such Channel" error, we disable the feature and say "nope, not supported here."

**Comment by rfk** [comment] 2017-06-01 09:52
If it's a simple fix, SGTM, thanks @shane-tomlinson

**Closed** 2017-06-01 21:12 UTC
Labels: train-88, waffle:review, ❤
