### ISSUE TITLE
Device list shows one device in quadruplicate

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3674] opened 2016-04-20 11:48 UTC
Though the feature hasn't shipped yet, when forced on, I can see that the device list shows one of my devices in quadruplicate, and none of my iOS devices.

<img width="532" alt="screenshot 2016-04-20 07 45 20" src="https://cloud.githubusercontent.com/assets/68213/14673431/eba88388-06cb-11e6-9157-1c0de9b3a7b2.png">

@rfk As we help users gain better control of what connects to their account, I really would like to see this feature happen. Should we be adding iOS and Android people to this repo? I don't see my iOS device here either.

**Comment by philbooth** [comment] 2016-04-20 12:04
@ryanfeeley, have you reset your account on that machine recently? I'm only guessing, but it's possible that the issue has already been fixed by https://github.com/mozilla/fxa-auth-db-mysql/pull/128. I'm not sure if that is deployed yet / when it got deployed / when your duplicate devices appeared, so I might be wrong.

Re: getting your other devices to show up in that view, we'll be starting work on https://github.com/mozilla/fxa-auth-server/issues/1196 soon, which should help. It was supposed to get done last quarter but I was slow on other stuff and then the whole attack thing happened.

**Comment by ryanfeeley** [comment] 2016-04-20 12:33
@philbooth If I did, it was "weeks ago". :)

I think, despite localization challenges, we're going to have to make that string more specific.

**Comment by rfk** [comment] 2016-04-20 21:30
>  I really would like to see this feature happen

Yes, I agree!

**Comment by rfk** [comment] 2016-04-20 21:31
I recall @shane-tomlinson being able to repro a similar problem when testing certain login flows, perhaps he can add more here.

**Comment by shane-tomlinson** [comment] 2016-04-21 12:46
> I recall @shane-tomlinson being able to repro a similar problem when testing certain login flows, perhaps he can add more here.

I can not recall how I got in that state.

**Comment by ryanfeeley** [comment] 2016-04-21 22:37
And also not sorted by last updated (soonest at top)

**Comment by rfk** [comment] 2016-08-17 00:31
Enough time has passed, that whatever device-registration bug caused this may well have been perturbed out of existence.  Since we don't have any clues for how to try reproducing, I'm going to close it out.  If it re-surfaces with renewed testing of the device view then let's try to capture more explicit STR.

**Closed by rfk** 2016-08-17 00:31 UTC
Labels: waffle:next
