### ISSUE TITLE
The account is still displayed after I delete it

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa-content-server#6983] opened 2019-02-21 10:41 UTC
Environment:
Devices: iPhone SE	12.0.1
Build: [Stage Train 131] and production;

Prerequisites:
Make sure you are logged with a valid account.

Steps to reproduce:
1. Go to 'manage account';
2. Tap on the 'Delete' button from the Delete account section;
3. Write your password and tap on Delete account;
4. Close and then reopen the app;
5. Tap on settings from the hamburger menu;

Expected result:
The account is not displayed.
 
Actual result:
The account is still displayed and if I tap on it, all the settings are displayed (sync, disconnect)

Notes:
-Not reproducible on the Android devices or Desktop;
-Video with the issue: https://drive.google.com/open?id=1p5BrrbcvTJmeoUzuZKxqPlCg8lsVwnCL

**Comment by shane-tomlinson** [comment] 2019-02-22 13:33
@sv-sdeiac thanks for the report. Some questions.

> The account is still displayed and if I tap on it, all the settings are displayed (sync, disconnect)

The account is displayed where, within FxA or within Firefox for iOS? If Firefox for iOS, this is a [known about problem with Firefox for iOS](https://bugzilla.mozilla.org/show_bug.cgi?id=1279333).

**Comment by sv-sdeiac** [comment] 2019-02-22 14:05
Sorry for my mistake, I was shared the wrong video.
There is the good video: https://drive.google.com/file/d/1ZLTk0Din9DVIxlWWTtNschnU9Yvz9cZ_/view?usp=sharing

**Comment by shane-tomlinson** [comment] 2019-02-22 14:37
Thanks @sv-sdeiac, yeah, that's caused by [Firefox for iOS not handling the `delete` notification that we send to them](https://bugzilla.mozilla.org/show_bug.cgi?id=1279333). Closing here.

Thanks for this, feel free to file any such issues here and we can re-triage as necessary.

**Closed by shane-tomlinson** 2019-02-22 14:37 UTC
