### ISSUE TITLE
Measure email bounces on sign-in confirmation emails

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4040] opened 2016-08-11 17:50 UTC
If we bounce the sign-in confirmation email, it means the user likely no longer has control of their account, and may wish to create a new account with a different email.

As a first step, we should measure instances of this (a second step will be how to handle it).

**Comment by vladikoff** [comment] 2016-08-15 16:29
from mtg: 

* soft bounces vs hard bounces, need a way to determine

**Comment by vladikoff** [comment] 2016-09-01 22:43
@vbudhram what was your plan for this? was it to use the same logic as https://github.com/mozilla/fxa-auth-server/pull/1431 or something else?

**Comment by vbudhram** [comment] 2016-09-02 02:36
@vladikoff I think for the first stage, I was going to add a check for type of view signup/signin [here](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/confirm.js#L148) and log the correct type of error. I'm not really sure how to differentiate the hard and soft bounces though or how to handle them for signin.

**Comment by rfk** [comment] 2016-09-02 03:37
My memory is fuzzy, but I don't think you'll be able to detect them there.  IIRC the content-server's `SIGNUP_EMAIL_BOUNCE` is a synthetic error that it creates when it's polling for account verification, and it suddenly receives a `102 ACCOUNT UNKNOWN` error.  It can then conclude that, well, the account *used* to exist but it doesn't any more, so it must have been deleted as the result of a bounce.

That logic won't work in the signin confirmation case, because we don't delete accounts that have already been verified:

  https://github.com/mozilla/fxa-auth-server/blob/master/lib/bounces.js#L44

So I suspect you'll need to look at server-side metrics for this.

**Comment by rfk** [comment] 2016-09-02 03:45
As a quick sanity-check, I added a graph of the existing `account.email_bounced.already_verified` event to the sign-in confirmation dashboard here:

  https://app.datadoghq.com/dash/163668/fxa-content---signin-confirmation

With the caveat we're not terribly confident in the accuracy of server-side events sent to datadog, it's interesting that there's at most a very small increase in the bounce rate as sign-in confirmation was rolled out:

![screen shot 2016-09-02 at 13 38 16](https://cloud.githubusercontent.com/assets/34695/18191981/3ba7cb9e-7113-11e6-9520-ae73178846a5.png)

Something like the flow-event work linked above may be a good way to get more reliable metrics on this.

**Comment by philbooth** [comment] 2016-10-03 21:33
See also: https://github.com/mozilla/fxa-auth-server/issues/1425

**Comment by rfk** [comment] 2016-10-03 22:17
@vbudhram I propose that we close this as a dupe of mozilla/fxa-auth-server#1425, and that whatever solution you had in mind for this, be expanded to the more general case discussed in that bug.

**Comment by vbudhram** [comment] 2016-10-04 00:33
@rfk Sounds good! I'll update auth-server PR accordingly.

**Closed by vbudhram** 2016-10-04 00:33 UTC
Labels: waffle:active
