### ISSUE TITLE
Addons.mozilla.org does not work in Firefox. Falsely claims "no cookies" when cookies are enabled.  It's a Made For Google Chrome Only website like so many websites now.

### ISSUE THREAD

**Issue by NothingCanPlayVTT** [mozilla/fxa-content-server#4778] opened 2017-03-03 03:37 UTC
I am getting sent on wild goose chases all over as to where to report this issue.  People say go here, then they send me somewhere else, and then they say go here.

Firefox version:
I am using the latest ESR 45.7.0 because each Firefox release gets slower and slower and slower like crazy so I had to switch to that until maybe Firefox fixes its slowdown. But that's the version I'm using if you need to narrow it down.

Steps to reproduce:

I go to
https://addons.mozilla.org/
It forwards me to
https://addons.mozilla.org/en-US/firefox/
I try to "log in" and click.
It sends me to this messy URL
https://oauth.accounts.firefox.com/v1/authorization?action=signin&scope=profile&state=77adf10ec56396afc38f7eab137aec9148aaefa649c7d6bcd6834c540307858d%3AL2VuLVVTL2ZpcmVmb3gv&redirect_url=https%3A%2F%2Faddons.mozilla.org%2Fapi%2Fv3%2Faccounts%2Fauthenticate%2F&client_id=a4907de5fa9d78fc

It then gives me this page:
------------------
Cookies and local storage are required.

Please enable cookies and local storage in your browser to access Firefox Accounts. Doing so will enable functionality such as remembering you between sessions.

Learn more

------------------
I checked and my cookies work just fine on every other website. Mozilla.org is NOT blocked from cookies. I click try again a million times. It just refuses to work.

I tried everything and it doesn't work in Firefox.

But it does work in Google Chrome. All these Corporate websites are all now made for Google Chrome only replacing made for MSIE only that sites were 15 years ago. So Addons.mozilla.org is made for Google Chrome only and doesn't work in its own browser.

**Comment by rfk** [comment] 2017-03-03 03:40
Hi @NothingCanPlayVTT, have you customized the privacy settings in Firefox in any way? Do you see the same issue if you create a brand new Firefox profile and try to login to the addons site through there?

**Comment by rfk** [comment] 2017-03-03 03:46
FWIW I'm able to log in successfully using ESR 45.7.0 on Windows, so I suspect it may be something specific to your Firefox setup.  Trying with a fresh Firefox profile will definitely help us narrow down the cause.

**Comment by shane-tomlinson** [comment] 2017-03-09 17:39
Thanks for the report @NothingCanPlayVTT, closing as dup of #4796.

**Closed** 2017-03-09 17:40 UTC
