### ISSUE TITLE
Sometimes forced to sign in to Sync twice, leaving a zombie session behind

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#4060] opened 2016-08-17 14:32 UTC
I'm not yet certain that this problem is in the content server, but raising it here for now so that I can do some further investigation.

When signing in to Sync using my hacked "legacy" device (Nightly with device registration disabled), it sometimes happens that sign-in confirmation succeeds but when I try to view my account I'm asked to sign in again. The original session is left alive and manifests itself as an extra item in the devices view that I must disconnect manually.

Need to figure out what is going wrong with the original session.

**Comment by philbooth** [comment] 2016-08-18 14:13
Not sure how much of a clue this is but I've noticed that, every time the problem occurs, the sign-in confirmation screen does not show the big blue `Sync preferences` button. Every time the sign-in works correctly, I can see the `Sync preferences` button.

Screenshot from one of the failing sessions:

<img width="789" alt="Sign-in confirmation screenshot from a failing session" src="https://cloud.githubusercontent.com/assets/64367/17776839/10a3fbf2-6556-11e6-9ef4-f4720009076b.png" />

Screenshot from a successful session:

<img width="790" alt="Sign-in confirmation screenshot from a successful session" src="https://cloud.githubusercontent.com/assets/64367/17776846/1c9ab16c-6556-11e6-8fd0-f06ec4ec3366.png" />

The problem occurs intermittently in the exact same browser session, without needing to restart or anything.

**Comment by rfk** [comment] 2016-08-18 20:59
The presence of "sync preferences" button is controlled by a property on the auth-broker.  Is it possible that we're somehow forgetting the correct auth-broker to use?

@philbooth have you ever seen the same behaviour on a non-hacked nightly?

**Comment by philbooth** [comment] 2016-08-18 21:04
> have you ever seen the same behaviour on a non-hacked nightly?

I haven't tried yet, been focusing on the device registration problems today. It's on my to-do list!

**Comment by philbooth** [comment] 2016-08-19 16:41
> have you ever seen the same behaviour on a non-hacked nightly?

Yep. I can reproduce it on vanilla installs of Nightly and Dev Edition.

However, I can't reproduce it against the production servers, I've only seen it in local dev (using both current master and with the train 67 tags checked out). So quite possibly something wrong with my set-up, although obviously I'll make sure I get to the bottom of it before closing this issue, just to be sure.

**Comment by philbooth** [comment] 2016-08-31 12:00
I can't reproduce this any more. Just signed in 20 times consecutively without seeing the problem (although, interestingly, I did see the missing `Sync preferences` button).

Anyway, closing this but will keep my eyes peeled for it happening again.

**Comment by philbooth** [comment] 2016-09-02 09:25
Unfortunately I just saw this in production using a local (unmodified) Nightly build. Re-opening.

**Comment by rfk** [comment] 2016-09-05 02:28
> every time the problem occurs, the sign-in confirmation screen does
> not show the big blue Sync preferences button. Every time the sign-in works correctly,
> I can see the Sync preferences button.

To clarify, are you opening the verification link in the original browser each time?

**Comment by rfk** [comment] 2016-09-05 02:31
Also to clarify, when you say:

> when I try to view my account I'm asked to sign in again. 

Does this mean you're e.g. using the "manage account" link in the sync preferences page?

**Comment by rfk** [comment] 2016-09-05 02:47
Ack, I was also able to reproduce this in nightly against production.  Interestingly, the browser itself seemed to be getting along just fine, it was only when I attempted to access FxA on the web that it forced me to re-auth and mucked up my browser session.

**Comment by philbooth** [comment] 2016-09-05 07:10
> To clarify, are you opening the verification link in the original browser each time?

Yep. Original browser, original tab (if that matters).

> Does this mean you're e.g. using the "manage account" link in the sync preferences page?

Yep, exactly that.

> I was also able to reproduce this in nightly against production.

Cool, thanks. From now on I'll run with extra logging in my local content server so I can be ready for when it happens again.

**Comment by philbooth** [comment] 2016-09-07 09:01
Related: https://bugzilla.mozilla.org/show_bug.cgi?id=1300762

**Comment by philbooth** [comment] 2016-09-30 09:05
More symptoms that I've noticed while debugging this locally.

After the initial sign-in confirmation succeeds, I click on `Manage account` and we try to navigate to `/settings` but end up back at the sign-in view. At this point I can see two errors in the console.

Error the first:

```
Session expired. Sign in to continue.  logger.js:74:11
	error http://127.0.0.1:3030/scripts/lib/logger.js:74:11
	captureError http://127.0.0.1:3030/scripts/lib/error-utils.js:45:7
	logError http://127.0.0.1:3030/scripts/views/base.js:562:7
	checkAuthorization/< http://127.0.0.1:3030/scripts/views/base.js:248:13
```
Error the second:

```
Invalid token  logger.js:74:11
	error http://127.0.0.1:3030/scripts/lib/logger.js:74:11
	captureError http://127.0.0.1:3030/scripts/lib/error-utils.js:45:7
	logError http://127.0.0.1:3030/scripts/views/base.js:562:7
	displayAccountProfileImage/< http://127.0.0.1:3030/scripts/views/mixins/avatar-mixin.js:62:11
```

Now I sign in again and, when I get to the confirmation screen, the auth server log goes totally cray cray because the content server is thrashing `/recovery_email/status` on a per-millisecond basis. To the point where this error appears in the console after I've pasted in the confirmation link:

```
Server busy, try again soon  logger.js:74:11
	error http://127.0.0.1:3030/scripts/lib/logger.js:74:11
	captureError http://127.0.0.1:3030/scripts/lib/error-utils.js:45:7
	logError http://127.0.0.1:3030/scripts/views/base.js:562:7
	_startPolling/< http://127.0.0.1:3030/scripts/views/confirm.js:142:11
```

(to be clear, the confirmation itself works this time and I am signed in correctly at this point)

**Comment by rfk** [comment] 2016-10-05 23:56
Maybe related to https://github.com/mozilla/fxa-content-server/issues/4060

**Comment by vladikoff** [comment] 2016-10-06 00:00
@rfk sorry what is related to #4060 ?

**Comment by rfk** [comment] 2016-10-06 00:00
Sorry, that was a copy-paste fail, I meant to link to https://bugzilla.mozilla.org/show_bug.cgi?id=1308038

**Comment by rfk** [comment] 2016-10-06 05:40
> the auth server log goes totally cray cray because the content server
> is thrashing /recovery_email/status on a per-millisecond basis.

For completeness, this turned out to be a separate issue that has since been fixed: https://github.com/mozilla/fxa-content-server/issues/4237

**Comment by rfk** [comment] 2016-10-06 05:41
IIUC the localStorage weirdness identified in https://github.com/mozilla/fxa-content-server/issues/4115#issuecomment-250741309 and onward, would also suffice to explain the issue here.

**Comment by vladikoff** [comment] 2016-11-14 21:28
from mtg: closing for now

**Closed by vladikoff** 2016-11-14 21:28 UTC
Labels: waffle:next

**Comment by shane-tomlinson** [comment] 2017-03-01 13:40
Ref https://github.com/mozilla/fxa-content-server/issues/4763
