### ISSUE TITLE
feat(oauth): Remember user session

### ISSUE THREAD

**Issue by gdestuynder** [mozilla/fxa-content-server#5916] opened 2018-02-15 16:43 UTC
Hi!

We've integrated FxA with Mozilla IAM/Auth0 as a POC:

https://www.youtube.com/watch?v=biKAL8y-aOk

One thing I noticed, is that the user has to login twice every time (once to start the auth0 session, once for the FxA authorization). I wondered if we would have interested to remember the user authorization for some time, in order to run into this "double login" scenario less often (specially in comparison with other providers)

**Comment by rfk** [comment] 2018-02-15 20:25
> One thing I noticed, is that the user has to login twice every time

Interesting, can you please share a video of this to be sure I understand what you mean?

I'd guess this is being caused by the logic here:

  https://github.com/mozilla/fxa-content-server/blob/e0bd497f918659421bacf2f9545002a46c6ffecc/app/scripts/views/sign_in.js#L247

Where we reason that:

"""
We need to ask the user again for their password unless the credentials came from Sync.
Otherwise they aren't able to "fully" log out. Only Sync has a clear path to disconnect/log out
your account that invalidates your sessionToken.
"""

But I don't think that's true any longer, we have a "sign out" button in the web view for sessions that not related to sync.  So ISTM we should be able to improve the situation here fairly easily.

**Comment by vladikoff** [comment] 2018-02-15 20:30
> Interesting, can you please share a video of this to be sure I understand what you mean?
https://www.youtube.com/watch?v=biKAL8y-aOk

**Comment by rfk** [comment] 2018-02-15 20:32
Ah, gotcha, I had missed that this video started with the user already signed in to FxA.

**Comment by gdestuynder** [comment] 2018-02-15 23:26
Hah yeah in this case my user wasn't logged in to Sync (I've another user in another profile for that) but had already logged into FxA in the video

**Comment by rfk** [comment] 2018-02-15 23:28
Is the experience improved if you're signed in to sync in that browser?

**Comment by gdestuynder** [comment] 2018-02-15 23:41
I suspect I have to change a bunch of `about:config` things for my user on latest-dev/dev to work with this? (since my kang+fxa@insecure.ws users does not exist on prod)

**Comment by vladikoff** [comment] 2018-02-16 02:57
@gdestuynder this will give u a "latest" profile https://github.com/vladikoff/fxa-dev-launcher/blob/master/README.md#basic-usage-example-in-os-x

**Comment by gdestuynder** [comment] 2018-02-17 00:47
thx

https://www.youtube.com/watch?v=aIT4wNx5_dc&feature=youtu.be

**Comment by rfk** [comment] 2018-02-20 02:49
Taking this, because I expect I'll need to address a similar issue as part of https://github.com/mozilla/fxa-content-server/issues/5703 anyway

**Comment by gdestuynder** [comment] 2018-03-02 18:45
**Answers**

> The difficulty is that there's potentially confusing behaviour around logging out of an FxA relier. If I use FxA to sign in to AMO, and then I sign out in AMO, I could reasonably expect to have to enter my password again if I want to sign back in. But we don't have a way for AMO to signal back to FxA that the user signed out.

This is a common issue and since we never control all the RPs (relying parties), it's one that I've never seen completely fixed. With Auth0 for example we support registering a "logout url" which will effectively "log you out of SSO" and **every single**  RP uses it (and uses it correctly) everything works as expected.  In reality of course only some do and most don't.

> I tried out the equivalent flow using the IAM -> AirMO integration, and this is what happened:

AirMo supports the centralized logout so it logs you out of SSO (at the moment at least, I could imagine a future where we just disable this because it can be confusing...). Slack won't for example.

Here is some doc from auth0 on how it works: https://manage-dev.mozilla.auth0.com/docs/logout
And the OpenID Connect standard for it (which auth0 does not currently follow) http://openid.net/specs/openid-connect-session-1_0.html#RPLogout

I think, again, one major issue with the OIDC standard is that it assumes you control all RPs and will make them all behave - in reality/in practice, it's not true at all for us though.

**Non-answers ;-)**
I don't believe we need or want to link logins/logout like a true SSO between FxA and Auth0. I would even say, I wouldn't want that as a user because it'd log me out of FxA elsewhere and that would annoy me.

As exposed above it's practically impossible to do "end to end" without complete control of all RPs code regardless. I think instead, I'd expect some sort of session that is held by FxA. I kind of like how GitHub does it (you can try by logging in to airmo or another property that uses our auth0 instance, then logging out, then back, etc. It will log out of SSO with airmo but not out of github. It will also ask you for confirmation if it detects you login several times in a short amount of time.

Note that the whole issue is not a requirement for us to onboard FxA on auth0/Mozilla IAM, just a UX thing that would be nice *in my opinion*.

Hope this helps!

**Comment by rfk** [comment] 2018-03-04 23:06
> I don't believe we need or want to link logins/logout like a true SSO between FxA and Auth0. I would 
> even say, I wouldn't want that as a user because it'd log me out of FxA elsewhere and that would
> annoy me.

Yes, particularly if you logged you out of Sync in your browser!

**Comment by rfk** [comment] 2018-03-04 23:06
> Note that the whole issue is not a requirement for us to onboard FxA on auth0/Mozilla IAM,
> just a UX thing that would be nice in my opinion.

I'm going to take this out of the IAM milestone for Q1 tracking purposes.

**Comment by vladikoff** [comment] 2018-06-08 04:50
@rfk @gdestuynder do we still want to do this ? or just close for now?

**Comment by rfk** [comment] 2018-06-08 05:15
I don't have a clear next step or priority here, I'm happy to close it out for now and bring it back as some concrete "implement XYZ logout flow" bugs if and when we decide to do it.

**Comment by vladikoff** [comment] 2018-06-08 05:28
🗡

**Closed by vladikoff** 2018-06-08 05:28 UTC
Labels: waffle:backlog
