### ISSUE TITLE
Asked me Login after Successful Login

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#5229] opened 2017-07-11 21:01 UTC
While filming for Send Tab with Spencer, I quickly created an account in a new profile and then did a login in another new profile.

After login, the firstrun page redirected to https://accounts.firefox.com/signin

I checked the browser and I was officially logged in and syncing so I did not need to login again. My state was just not detected.

I was running 55.0b5 (64-bit) on Mac OS.

**Comment by shane-tomlinson** [comment] 2017-07-11 21:15
@davismtl - do you remember the steps you used to get there, on which browser/device/os combo?

**Comment by shane-tomlinson** [comment] 2017-07-11 21:15
> After login, the page redirected to https://accounts.firefox.com/signin

Which page redirected to the /signin page?

**Comment by shane-tomlinson** [comment] 2017-07-11 21:16
> device/os combo?

I'm tired and not thinking/reading straight, you said that in:

> I was running 55.0b5 (64-bit) on Mac OS.

**Comment by davismtl** [comment] 2017-07-11 21:41
> Which page redirected to the /signin page?
I did login from the sign-in form on first run (I specifically clicked "Already have an account").

**Comment by shane-tomlinson** [comment] 2017-07-12 11:02
>  I quickly created an account in a new profile and then did a login in another new profile.

Did you verify the account before signing in in the 2nd browser? Did you have to confirm in the 2nd browser?

**Comment by shane-tomlinson** [comment] 2017-07-12 11:09
AAAGH!

![sign-up-sign-in](https://user-images.githubusercontent.com/848085/28114973-fc9e9548-66fa-11e7-8a04-3b03e7ea39bd.gif)

**Comment by shane-tomlinson** [comment] 2017-07-12 11:20
This reproduces on both Firefox 55 and Firefox 56 when signing in from the firstrun page.

**Comment by shane-tomlinson** [comment] 2017-07-12 14:08
This has the same root cause as https://github.com/mozilla/fxa-content-server/issues/5209.

Because firstrun is considered a Sync flow, no account information is written to localStorage because we assume the browser will always respond with account information when requested. Upon successful login, FxA sends a `login` message to the firstrun page, causing the firstrun page to open https://accounts.firefox.com/settings, without any query parameters.

[A bug (that I wrote) causes Firefox to assume it's in private browsing mode if no service is specified](https://bugzilla.mozilla.org/show_bug.cgi?id=1378766), when visiting https://accounts.firefox.com/settings, Firefox refuses to return the currently signed in user information.

<img width="718" alt="screen shot 2017-07-12 at 14 43 33" src="https://user-images.githubusercontent.com/848085/28121173-303689d0-6712-11e7-9ffa-217b2969e715.png">


Since no account information was written to localStorage on signin, the settings page believes no user is signed in, and it redirects to /signin.

This is backed up by the following screen cap which shows that /settings *will* load if `?service=sync` is specified:

![no-service-service](https://user-images.githubusercontent.com/848085/28121126-0d11ce7e-6712-11e7-9938-6d8c0a7e53b6.gif)

While digging in, I noticed another [potential timing problem](https://github.com/mozilla/fxa-content-server/blob/d13cbd5d1ae893ebaaffcd6fb6627142176e2783/app/scripts/models/auth_brokers/fx-firstrun-v1.js#L63).

[The firstrun page](https://github.com/mozilla/fxa-content-server/blob/d13cbd5d1ae893ebaaffcd6fb6627142176e2783/app/scripts/models/auth_brokers/fx-firstrun-v1.js#L63) is notified of login [*before* the browser](https://github.com/mozilla/fxa-content-server/blob/d13cbd5d1ae893ebaaffcd6fb6627142176e2783/app/scripts/models/auth_brokers/fx-firstrun-v1.js#L65). If the firstrun page redirects before the `fxaccounts:login` message is received by the browser, it's possible for the `fxaccounts:login` message to never be sent. If the `fxaccounts:login` message is never sent, the browser won't realize that a user has signed in.

Some possible mitigations:

1. Fix the browser bug (best) - https://bugzilla.mozilla.org/show_bug.cgi?id=1378766
2. Have the firstrun page redirect to https://accounts.firefox.com/settings?service=sync (with ?service=sync) to work around the browser bug.
3. Stop sending the login message to the firstrun page and instead redirect users who sign in to `/signin_complete`

More thought needed.

**Comment by shane-tomlinson** [comment] 2017-07-12 16:22
I have filed a Firefox patch here: https://reviewboard.mozilla.org/r/156572/diff/1#index_header

**Comment by davismtl** [comment] 2017-07-12 16:41
@shane-tomlinson Is there something we can do on our end to avoid waiting for the patch to make it into Firefox?

For example, we know it happens when entrypoint=firstrun.

**Comment by shane-tomlinson** [comment] 2017-07-12 16:50
> @shane-tomlinson Is there something we can do on our end to avoid waiting for the patch to make it into Firefox?

@davismtl - There are a couple of possible partial solutions outlined above. They'll work around this problem, but not the problem @vladikoff outlined in #5209.

> 2. Have the firstrun page redirect to https://accounts.firefox.com/settings?service=sync (with ?service=sync) to work around the browser bug.
> 3. Stop sending the login message to the firstrun page and instead redirect users who sign in to /signin_verified

Either option is fairly straight forward. Option 2 preserves existing behavior, option 3 changes behavior to end in this screen:

<img width="493" alt="screen shot 2017-07-12 at 17 49 42" src="https://user-images.githubusercontent.com/848085/28129236-82c413b2-672a-11e7-9234-1379da76d329.png">

The most difficult part of Option 3 will be updating the functional tests.

**Comment by davismtl** [comment] 2017-07-12 17:08
Are there any down sides to not sending login message to firstrun?

What I like about option 3 is that we can make the change on our end without another team. (even if it requires changes to functional test)

Also, I already hated the fact that we sent users to Settings. This page isn't much better but a small improvement.

**Comment by shane-tomlinson** [comment] 2017-07-12 20:19
> Are there any down sides to not sending login message to firstrun?

The firstrun team [sends a message to GA](https://github.com/mozilla/bedrock/blob/55bead0e3dd8be7de19d4db7851c232e09c780f0/media/js/base/mozilla-fxa-iframe.js#L200) to track the # of logins. This number will already be skewed though, users that go through signin confirmation do not cause the `login` message to be sent to the firstrun page.

Option 3 then?

**Comment by davismtl** [comment] 2017-07-12 20:22
Yeah.

Can we make recommendations on how to fix GA tracking of login?

**Comment by davismtl** [comment] 2017-07-12 20:24
Follow up, would registration tracking in GA be impacted the same way?

**Comment by vladikoff** [comment] 2017-07-13 01:50
This was fixed. https://bugzilla.mozilla.org/show_bug.cgi?id=1380412#c3

**Comment by vladikoff** [comment] 2017-07-13 01:50
Nevermind, different issue

**Comment by shane-tomlinson** [comment] 2017-07-13 12:56
> Can we make recommendations on how to fix GA tracking of login?

I don't have a recommendation at this time, we should find out whether they
actually use the number. Ever since we added signin confirmation, their
numbers would have been off since the `login` message was only sent
for users that didn't need to confirm the signin.

**Comment by davismtl** [comment] 2017-07-13 17:53
I confirm that they use it. I was actually coincidentally asked about its accuracy 2 days ago. I said I had doubts and this conversation confirmed my suspicion.

**Comment by shane-tomlinson** [comment] 2017-07-18 12:59
A tentative Bedrock only fix has been shipped that causes the firstrun page to open /settings with the `?service=sync` query parameter, which works around the browser bug.

**Comment by shane-tomlinson** [comment] 2017-07-19 08:52
Closing as fixed by bedrock. We can open additional bugs as needed.

**Closed by shane-tomlinson** 2017-07-19 08:52 UTC
Labels: waffle:active
