### ISSUE TITLE
Quitting Firefox before choosing what to sync results in verification error

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3501] opened 2016-02-11 16:27 UTC
CURRENT
1. Start new profile in Nightly
2. Register a new sync account
3. Before choosing what to sync, quit browser
4. Verify on another device
5. Get "Verification error"
6. Return to original browser, account is not in unverified state
7. Account verified email sends

EXPECTED
5. Account verified screen shown succesfully
6. When returning to original browser, account be polled presenting web page to user choose what to sync

![img_7390](https://cloud.githubusercontent.com/assets/68213/12982513/13554636-d0b3-11e5-9956-ea1312c4520e.PNG)

**Comment by vladikoff** [comment] 2016-02-11 16:36
Cannot reproduce this, the verification issue could be unrelated

**Comment by ryanfeeley** [comment] 2016-02-11 16:37
@vladikoff What do you see?

**Comment by vladikoff** [comment] 2016-02-11 16:38
> @vladikoff What do you see?


5. Account verified screen shown succesfully

**Comment by ryanfeeley** [comment] 2016-02-11 16:40
@vladikoff But what state is the originating browser in? Do you have to sign in to Sync as if it's never been done before?

**Comment by vladikoff** [comment] 2016-02-11 16:41
@ryanfeeley I followed these steps:

> 1. Start new profile in Nightly
2. Register a new sync account
3. Before choosing what to sync, quit browser

**Comment by ryanfeeley** [comment] 2016-02-11 16:43
@vladikoff Can you start up the browser again and tell me what state it's in?

**Comment by vladikoff** [comment] 2016-02-11 16:48
@ryanfeeley I think i have it in state that you describe as "Do you have to sign in to Sync as if it's never been done before"

**Comment by ryanfeeley** [comment] 2016-02-11 16:51
@vladikoff I wonder if we can look at our ux metrics to see how often this is happening. I imagine this is quite a few people as few would sign in when the browser is in that state.

**Comment by rfk** [comment] 2016-02-11 20:12
> I think i have it in state that you describe as "Do you have to sign in to
> Sync as if it's never been done before"

IIUC this is because we don't fire the webchannel event telling the browser to sign-in until after we've got the sync data choices, so as far as the browser knows you haven't done anything yet.  To do a good job of it we'll have to introduce some split state in the browser, so that "the user logged in" and "the user is ready to start syncing now" can be sent as two separate events.

Definitely worth getting metrics on how often this happens.

**Comment by shane-tomlinson** [comment] 2016-02-11 20:43
> IIUC this is because we don't fire the webchannel event telling the browser to sign-in until after we've got the sync data choices, so as far as the browser knows you haven't done anything yet.

Yup, this is the flow. As an aside, the OAuth permissions screen suffers from this problem too. The verification email is sent as soon as the first submit button is pressed. The user can be sitting at the permissions screen whenever they verify in another tab. I've never tried this and do not know what happens.

> To do a good job of it we'll have to introduce some split state in the browser, so that "the user logged in" and "the user is ready to start syncing now" can be sent as two separate events.

An alternative, possibly simpler, proposal:

Use the "is this email address registered" API endpoint that @vbudhram is working on. When the user clicks "submit" on the signup page, don't sign up (like we currently do). Instead, check whether the email is registered. The key is we need to know whether the email is registered *and verified*. Just registered is not enough, because a user who has signed up and not verified can sign up again with a new password. If the email is not signed up and verified, send the user to CWTS. When the user completes CWTS, sign up the user and notify the browser.

This proposal fixes multiple problems:

1. Expectations are better met that an email is not sent until the signup flow is completed. Receiving an email midway through the flow feels "off."
1. Users who do not complete CWTS and verify their email addresses are not currently signed in to Sync. Unless the user figures out they need to sign in again from about:preferences#sync, these users receive no value from FxA and probably drop off. If these users are not signed up to begin with, our overall signup numbers may drop but our retention numbers should increase.

>
> Definitely worth getting metrics on how often this happens.

@ryanfeeley believes its about 5%. 5% of a very large number is a large number. So far the number is low because CWTS on the web is only enabled for Fennec, iOS v2, and FxDesktopV2. For FxDesktop this is Fx >= 44. Once #3493 and the corresponding firstrun patches land, many more users will be exposed.

Ref #3502

**Comment by ryanfeeley** [comment] 2016-02-11 21:25
If my math is right on "% of non-Android CWTS drop-off” it’s even worse on desktop (7%).

**Comment by vladikoff** [comment] 2016-02-16 17:46
Connection error. closing

**Closed by vladikoff** 2016-02-16 17:46 UTC
