### ISSUE TITLE
Odd. Tests fail with Fx Beta on fxadev boxes, but pass on stage with Fx Beta

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#5844] opened 2018-01-22 21:07 UTC
Can't really explain this. Missing config/feature? 

(Yes, stage is currently train-103, but this has been true for a while).

https://tc-test.dev.lcip.org/

Actually, a better comparision is really `nightly` vs. `latest`.dev.lcip.org

**Comment by jrgm** [comment] 2018-01-22 21:24
Something about change email?

**Comment by vbudhram** [comment] 2018-01-22 23:53
Dug into this a little and found that `secondary_emails` and `change_email` tests pass on `latest.dev.lcip.org` with FF57 but fail with FF58. It might be unrelated but the tests should have still passed.

I suspect there might be a subtle timing difference that is causing the test flakiness. I'll try to put up a PR at gets these tests passing for both FF.

**Comment by jrgm** [comment] 2018-01-24 20:16
So, the firefox versions on the test host automatically updated. So now release is 58, and beta 59, and all the test failures with "beta" disappeared. ¯\_(ツ)_/¯

**Comment by vbudhram** [comment] 2018-01-25 17:53
from mtg: Can't reproduce, closing..

**Closed by vbudhram** 2018-01-25 17:53 UTC
Labels: train-105, waffle:active
