### ISSUE TITLE
Sign-in gets stuck at "working..."

### ISSUE THREAD

**Issue by grigoryk** [mozilla/fxa-content-server#5215] opened 2017-07-07 21:35 UTC
For some reason I got logged-out after upgrading my Nightly, and trying to sign back in results in a perpetual "Working...." state.

POST to `login?keys=true` succeeds with a 200, and then things get stuck.

![jdqs7dn](https://user-images.githubusercontent.com/465422/27977858-99c6b0ae-633a-11e7-93b7-a01ff4892145.jpg)
![rpd3vgn](https://user-images.githubusercontent.com/465422/27977859-99ca4d86-633a-11e7-8d26-42076a491c24.png)

**Comment by grigoryk** [comment] 2017-07-07 21:39
At the same time, "New sign-in to Firefox" emails are coming through.

**Comment by grigoryk** [comment] 2017-07-07 22:04
Disconnecting and trying to sign-in gets me to the same stuck state.

**Comment by shane-tomlinson** [comment] 2017-07-07 22:30
@grigoryk - this is symptomatic of a WebChannel problem. In about:config, if you search for `fxaccounts`, are all the values other than `identity.fxaccounts.lastSignedInUserHash` the default value? Usually this occurs if `identity.fxaccounts.remote.webchannel.uri` is either not set, or set to something other than `https://accounts.firefox.com/`

**Comment by grigoryk** [comment] 2017-07-07 22:43
@shane-tomlinson it all looks OK to me: http://i.imgur.com/aBPMlZY.jpg

**Comment by jrgm** [comment] 2017-07-07 22:45
I'll note that this issue was filed right about the same time that content train-90 went live (live at 21:32; this issue filed at 21:35).

**Comment by jrgm** [comment] 2017-07-07 22:45
> content train-90 went live

I rolled back at 21:56Z.

**Comment by grigoryk** [comment] 2017-07-07 22:46
Unsure if this is related at all, but I'm also seeing the following errors in the console if I open `about:accounts` from the Sync Preferences screen via Sign-In button:

`

        Unexpected error 78a28dde.main.en.js:17:4002
	error main.js:18148:10

	captureError main.js:20403:19

	captureAndFlushError main.js:20433:6

	fatalError main.js:20473:20

	fatalError main.js:27299:13

	D main.js:19999:11

	C main.js:19988:3

	l main.js:19704:3

**Comment by jrgm** [comment] 2017-07-07 22:47
> I rolled back at 21:56Z.

content-only rollback. I could rollback live auth and oauth if desired.

**Comment by jrgm** [comment] 2017-07-07 23:25
I rolled back the oauth and auth servers just now. So everything (modulo a db migration) is back to what was running in production this morning.

**Comment by grigoryk** [comment] 2017-07-07 23:30
@jrgm and I was just able to sign-in on all my devices, although in a bumpy and confusing way. See my actions in https://github.com/mozilla/fxa-content-server/issues/5216

**Comment by shane-tomlinson** [comment] 2017-07-10 11:10
@grigoryk - I'm trying to reproduce against stage and locally, but have so far been unable to. Some questions to see if we can figure this out:

1. Which version of Nightly were you using?
2. On which OS? (My guess is CentOS from http://i.imgur.com/aBPMlZY.jpg)
3. Was the account new, i.e., created within the past 24 hours?
4. Was another user already signed in? I see the little "verify your email" icon in the upper right hand corner.
5. Since you used a @mozilla.com email address, were you asked to enter an unblock code?

**Comment by grigoryk** [comment] 2017-07-12 22:37
I got logged out again, I'm now seeing this behaviour again, on the current Nightly 56 and on 54. Pressing "Reconnect to Sync" brings me to a Create Account page, generally seeing the flow I've described in https://github.com/mozilla/fxa-content-server/issues/5216 but on Desktop.

I'm trying all of this with my regular (rather old) account.

e10s is disabled on my Firefox 54. It is enabled on Nightly.

**Comment by grigoryk** [comment] 2017-07-12 22:39
I can't get past the sign-in form, so I don't see any requests for unlock codes. Neither do I get an email with one. I do see emails such as "new sign-in", and before "confirm sign-in" after every attempt to login in the browser.

**Comment by vladikoff** [comment] 2017-07-12 23:04
https://bugzilla.mozilla.org/show_bug.cgi?id=1380412#c1

**Comment by vladikoff** [comment] 2017-07-12 23:04
We are working on a DB fix for this...

**Comment by jbuck** [comment] 2017-07-12 23:55
See https://bugzilla.mozilla.org/show_bug.cgi?id=1380412#c3

**Closed** 2017-07-13 01:35 UTC
Labels: waffle:blocked
