### ISSUE TITLE
Email-opt outs do not seem to take effect from /settings.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5465] opened 2017-09-11 09:25 UTC
I noticed this while signing up for a test account, I opted into the marketing email. I went to settings and opted out. I still receive the marketing emails. Others noticed similar behavior.

**Comment by rfk** [comment] 2017-09-12 04:52
Some emails, such as "you're not yet syncing a second firefox", do out to all users regardless of their setting here.  Which email did you get that you weren't exepcting?

**Comment by shane-tomlinson** [comment] 2017-09-12 08:34
> Which email did you get that you weren't expecting?

I received "How are things going?" yesterday.

**Comment by rfk** [comment] 2017-09-13 02:22
@davismtl can you clarify which emails are covered by the marketing opt-in, and which are "transactional" and appear for all users?  This "how are things going" certainly feels like it should have been opt-in :-)

**Comment by davismtl** [comment] 2017-09-13 17:14
"How are things going?" is suppose to be their last onboarding email sent (4 of 4). Asking for feedback during onboarding emails is totally acceptable and within the rules of onboarding messages. Asking to set us as default is also acceptable if it allows to get the best out of our product. Though the super friendly tone does make it feel very marketing. :-/ Hard to balance efficiency and personality/branding.

Perhaps putting somewhere "Welcome email 1/4" would make it more tolerable? 

Note you can see what emails they've tested up until now and what they've been measuring:
https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=67305796

There conclusion in the doc seems incomplete and there are some results missing so I've asked to clarify and update the mana page.

I have also noticed that though it is not necessary, they still added unsubscribe links to their 4 onboarding emails. This is great and certainly best practice! I'm wondering if we should add that as a second checkbox in communication preferences. Thoughts?

**Comment by davismtl** [comment] 2017-09-13 18:30
update:
Those 4 emails that I linked to are meant to be opt-in, not transactional.

I'm not sure why Shane got them. Is there a 24h delay for opt-out or do we push the opt-out immediately?

**Comment by rfk** [comment] 2017-09-18 05:16
> Is there a 24h delay for opt-out or do we push the opt-out immediately?

We tell basket about it immediately, I'm not sure how it's processed downstream of that.  We may need to get Ben to help debug this.

**Comment by davismtl** [comment] 2017-09-18 19:23
I've messaged Ben to take a look at this thread.

**Comment by mwarther** [comment] 2017-09-22 16:38
@davismtl we are putting all the current programs that would touch an FxA holder into the doc that Ryan Feeley created and will update the mana page too.

**Comment by mwarther** [comment] 2017-09-22 16:46
@davismtl I can only suggest on Ryan's document if you'd add me as an editor too.

FYI the mana page for the "how are things going" email for lapsed Firefox Accounts holders is here https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=68552099 the one about is for subscribers to our Firefox email programs only

**Comment by rfk** [comment] 2017-09-25 05:31
So here's one thing I noticed.  STR:

* Create a new account, checking the "receive the monthly Firefox newsletter" checkbox.
* Verify the account.
* Go to https://accounts.firefox.com/settings/communication_preferences
* Observe that the button says "unsubscribe" indicating that you're subscribed: <img width="357" alt="capture" src="https://user-images.githubusercontent.com/34695/30793498-bb3d491e-a205-11e7-8eb5-5207e3354477.PNG">
* Click the "email preferences" link, which opens in a new tab
* Observe that you're subscribed to both "Firefox + You" and "Firefox Accounts Tips": <img width="433" alt="capture" src="https://user-images.githubusercontent.com/34695/30793517-e08e87e6-a205-11e7-8a84-1152e82fe3d0.PNG">
* Close that tab, go back to FxA and click the "unsubscribe" button
* Observe that the button changes to "subscribe": <img width="362" alt="capture" src="https://user-images.githubusercontent.com/34695/30793535-0e4fd374-a206-11e7-86a7-d83dcb5a7d76.PNG">
* Click on "email preferences" again

**Expected:**

* I should be unsubscribed from the things that the checkbox on the new-account page signed me up for

**Actual:**

* I'm still subscribed to "Firefox + You", and the "Firefox Accounts Tips" option is no longer present: <img width="426" alt="capture" src="https://user-images.githubusercontent.com/34695/30793587-55020094-a206-11e7-9b36-bc646d44f429.PNG">

Am I right in expecting that this process should unsubscribe me from "Firefox + You"?

**Comment by vladikoff** [comment] 2017-09-25 17:50
@davismtl ^

**Comment by davismtl** [comment] 2017-09-25 17:59
I let @bniolet1 know about this. He will help us investigate today.

**Comment by bniolet1** [comment] 2017-09-25 19:07
Ah. I think I know what's going on. 

The Unsubscribe / Subscribe button is working the way we (marketing and FxA) intended it to back when we (marketing) first started sending email to Firefox Accounts users (April 2016 or so). Back then it was subscribe only and the button turned this email program off or on. 

Since then we changed up who gets email (no longer opt-in only) and none of us remembered to change how this button works. We are currently sending Sync emails to EN accounts that don't have a second device connected in the first few days. These are sent regardless of a user's opt in status for email. 

Since the original emails (there was a four-message series that focused on Sync) were opt-in only, the button stopped the flow of Accounts messages since it switched off the "Firefox Accounts Tips" flag, which only appears in the preference center if you are subscribed to it (this is a setting in Basket and is easily changeable). 

So the issue is: if a user clicks unsubscribe they likely would expect to not receive any more email from us. But Basket is not currently being told to unsubscribe the user from anything other than Firefox Accounts Tips, which isn't really a subscription that does much on the back-end. 

I think the fix is to have the button tell basket to flip the flag for the slug "mozilla-and-you"

If I'm correct about what is happening, the button is currently flipping the flag for "firefox-accounts-journey"

**Comment by rfk** [comment] 2017-09-25 22:36
> If I'm correct about what is happening, the button is currently flipping the flag for "firefox-accounts-journey"

Correct.  But IIUC there's some magic in basket that when a user subscribes to "firefox-accounts-journey" they also get subscribed to "mozilla-and-you"?  Otherwise I'm not sure how users wind up in the "mozilla-and-you" bucket because I don't think we do that subscription explicitly.

**Comment by bniolet1** [comment] 2017-09-26 02:35
That's true. Basket sets the flags for Mozilla and you. But there isn't a mechanism in basket to undo a subscription.

**Comment by rfk** [comment] 2017-09-26 02:41
So it sounds like the only plausible fix here is for us to have the "communication preferences" control both "firefox-accounts-journey" and "mozilla-and-you"?  I wonder if this would negatively affect people who happened to subscribe to mozilla-and-you from outside of the FxA signup process.

**Comment by bniolet1** [comment] 2017-09-26 02:42
What if subscribe worked the same way but instead of unsubsidized we just sent them to the email preference center?

**Comment by davismtl** [comment] 2017-09-26 20:59
I like that idea. 

To be sure I understand...
Subscribe remains the same but instead of unsubscribe we put "Manage Subscriptions" and link to the preferences centre.

**Comment by rfk** [comment] 2017-09-26 21:01
There was a lot of complex back-and-forth went into us having a "subscribe/unsubscribe" button directly in the page, rather than just a link out to the prefs center.  I'll see if I can dig it up from the archives...

**Comment by bniolet1** [comment] 2017-09-26 21:17
@Alex, that's what I'm thinking.



Ben Niolet | Email Marketing Manager
Mozilla | bniolet@mozilla.com

**Comment by rfk** [comment] 2017-09-27 06:04
Hrm, the original design discussion was here:

  https://github.com/mozilla/fxa-content-server/issues/2443

And there are comments there suggesting we have just the outbound link to "email preferences", but the final version that landed included an inline "subscribe" button, and I don't see any of the discussion about why we wound up with that choice.

**Comment by davismtl** [comment] 2017-09-27 18:10
To you point, I don't see anywhere in the thread that says we can't do it. In fact, it seems to me that it's the second time that marketing is proposing a simple solution. :)

@ryanfeeley any reason you can think of for why @bniolet1 solution wouldn't work?

**Comment by ryanfeeley** [comment] 2017-09-27 18:15
That sounds great! Offers more granularity and seems more durable.

So if not subscribed buttons are:
<img width="483" alt="image" src="https://user-images.githubusercontent.com/68213/30929952-20d0422a-a38e-11e7-8867-6c532393014d.png">

And if subscribed, buttons are:
<img width="483" alt="image" src="https://user-images.githubusercontent.com/68213/30929996-48b5f8f2-a38e-11e7-82cd-bd5657c940ab.png">



Am I getting that right?

**Comment by bniolet1** [comment] 2017-09-27 19:03
This is exactly what I was thinking @rfeeley. Let's do to this.

And with the copy changes I think this is very transparent and gives users
a lot more clarity and control.

Ben Niolet | Email Marketing Manager
Mozilla | bniolet@mozilla.com

**Comment by vladikoff** [comment] 2017-10-02 21:00
@ryanfeeley has some ideas..

**Closed** 2017-10-17 14:56 UTC
Labels: train-98, waffle:review
