### ISSUE TITLE
"Account updated" notification is unreadable: dark font size on dark green

### ISSUE THREAD

**Issue by grigoryk** [mozilla/fxa-content-server#5445] opened 2017-09-07 03:55 UTC
It doesn't look _that_ bad on one of my monitors (terrible on the other), but it's certainly not very readable on my phone's screen.

![screenshot_1504756333](https://user-images.githubusercontent.com/465422/30145332-a9b3a784-935e-11e7-99ed-6bd6dd038299.png)

**Comment by philbooth** [comment] 2017-09-07 06:52
Thanks for the report, @grigoryk!

Actually a fix for this got made last week in #5421, which should reach production next week as part of train 95. Closing this as a dupe of #5418.

**Closed by philbooth** 2017-09-07 06:52 UTC
