### ISSUE TITLE
Disable web sessions until quality has improved

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4987] opened 2017-04-24 21:58 UTC
Alex and I are all reviewing device manager of the Sync team, and I have also received a screenshot from our copywriter with similar issues.

STEPS TO REPRODUCE
1. Create a Firefox Account for Sync
2. Sign in other devices
3. Sign in to Add-ons, Pockets, other sessions.
4. Upgrade a Firefox
5. Visit device manager

EXPECTED RESULTS
* List of devices, apps and web sessions appears and is manageable for a user syncing a few devices

ACTUAL RESULTS
* Duplicate web sessions
* Web sessions duplicated when browser updates
* Some sessions have "null" for client
* Some sessions are entirely blank

And and I are in agreement that we need to back out this feature ASAP and resolve quality issues.

**Comment by rfk** [comment] 2017-04-25 01:19
Ack; @vladikoff can you please make the necessary config adjustments for this feature flag?

> Web sessions duplicated when browser updates

This is a new one on me, does it reproduce reliably with a simple version update?

**Comment by rfk** [comment] 2017-04-25 01:20
@davismtl let's put this on the agenda for next FxA product meeting.

**Comment by davismtl** [comment] 2017-04-25 18:03
I agree. Here is what it looks like in my browser:
<img width="530" alt="screen shot 2017-04-25 at 11 02 20 am" src="https://cloud.githubusercontent.com/assets/19537086/25400255/d378f7f8-29a6-11e7-8855-37f43a78fe53.png">

**Comment by rfk** [comment] 2017-04-25 22:18
@vladikoff reminds me that we just removed the feature-flag for this, in https://github.com/mozilla/fxa-content-server/pull/4964

**Comment by rfk** [comment] 2017-04-25 22:29
So IIUC we'll need to:

* Revert https://github.com/mozilla/fxa-content-server/pull/4964
* Remove the version-gating logic, leaving the feature disabled for everyone unless they explicitly opt-in via query parameter
* Regroup and figure out what to do about the unexpected behaviors identified above

**Comment by rfk** [comment] 2017-04-27 03:10
They're now disabled in production, and I've filed follow-up issues for specific concerns raised here.  Closing out the issue.

**Closed by rfk** 2017-04-27 03:10 UTC
Labels: waffle:active
