### ISSUE TITLE
Confusing device name in my device list

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-content-server#5210] opened 2017-07-06 16:16 UTC
<img width="584" alt="screen shot 2017-07-06 at 9 14 57 am" src="https://user-images.githubusercontent.com/2365255/27921149-b117b3bc-622b-11e7-8227-d8d56b093572.png">

I think that's a Nightly install of Fennec on Android.

**Comment by vladikoff** [comment] 2017-07-06 16:30
This is coming from Android source it seems: https://searchfox.org/mozilla-central/search?q=Go+to+settings&path=

![image](https://user-images.githubusercontent.com/128755/27921717-9f1ace2c-6246-11e7-9a9e-d970ebd64a03.png)

@eoger @grigoryk ideas ?

**Comment by grigoryk** [comment] 2017-07-07 20:39
@ckarlof were you using tab queues at all?

**Comment by ckarlof** [comment] 2017-07-07 22:13
No (or at least not intentionally).

**Comment by ckarlof** [comment] 2017-07-07 22:14
Remind me how those are used? I might have been experimenting with those and don't remember.

**Comment by grigoryk** [comment] 2017-08-11 01:14
@ckarlof oops, notifications are not my strong suite it seems. Response a month later is better than never!

That's something you can enable in settings, and Fennec will prompt you to enable it if you're opening a lot of external links. Say, you're in the twitter client. You tap on links, and they're added to the queue. You'll see a notification in the notification bar, something akin to "you have 5 tabs pending". Clicking on that will get all of them open as tabs in Fennec.

No idea how the two could be connected yet (from looking at the code, they're not at all); IIRC that particular string is part of the tab queues UI - we ask you to go to settings to enable it.

A while back, sometime late June I think, we had a bug where Android strings got all mixed up in nightly UI - e.g. history panel would be called "settings", or "advanced", etc. This was due to a regression after a big change to the build system.

Perhaps what you see here is a weird manifestation of that bug. Have you seen any newly added devices with similarly odd names since?

**Comment by ckarlof** [comment] 2017-08-12 16:37
No, I haven't seen anything odd since.

**Comment by vladikoff** [comment] 2017-09-14 16:48
Closing. Seems like an Android problem

**Closed by vladikoff** 2017-09-14 16:48 UTC
Labels: waffle:backlog
