### ISSUE TITLE
Weird link behavior for Privacy Notice and Terms of Service on Desktop

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2504] opened 2015-06-01 23:57 UTC
### Steps to reproduce:
1. Go to https://accounts.firefox.com/legal/privacy

### Actual results:
![privacy_notice__things_you_should_know_](https://cloud.githubusercontent.com/assets/557895/7925855/be8c0178-087e-11e5-9ce3-35b53c0fd017.png)
I'm testing on Firefox 38.0.5 (Release) and the links aren't clickable or selectable. I have to manually type out the URL if I want to check the referenced links.

### Expected results:
I thought this change was only supposed to be for iOS/Android and possibly the iframe (but even forcing people to retype links in iframed environment would be mean).

**Comment by pdehaan** [comment] 2015-06-01 23:57
Ref: #2337

**Comment by pdehaan** [comment] 2015-06-02 00:00
Same w/ the Terms of Service page, here:

![terms_of_service](https://cloud.githubusercontent.com/assets/557895/7925915/96992988-087f-11e5-90ce-8c62f1847b18.png)

**Comment by vladikoff** [comment] 2015-06-02 03:50
@pdehaan I think this is by design, I raised concern about this in the PR when this was merged. Not sure about selection though.

**Comment by vladikoff** [comment] 2015-06-02 13:30
@pdehaan see https://github.com/mozilla/fxa-content-server/pull/2337#issuecomment-96352625

**Comment by pdehaan** [comment] 2015-06-02 16:31
Laaaammmmeee...
Lets change it. Breaking links on desktop is weak.

**Comment by vladikoff** [comment] 2015-06-02 16:35
ping @johngruen

**Comment by johngruen** [comment] 2015-06-03 20:50
@vladikoff agree with @pdehaan . Links should be disabled everywhere (ios, ffos, android, iframe) except vanilla desktop contexts.

**Comment by vladikoff** [comment] 2015-06-03 21:54
From that issue I linked:

> @johngruen asked for the links to be replaced universally.

Okay, seems like we didn't communicate this well enough, but no big deal, should be an easy fix. Thanks for responding!

**Comment by vladikoff** [comment] 2016-01-19 00:51
This was fixed!

**Closed by vladikoff** 2016-01-19 00:51 UTC
Labels: good-first-bug, waffle:backlog
