### ISSUE TITLE
exceptions on train-110 metrics route

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#6137] opened 2018-04-30 20:56 UTC
On POST	/metrics => 200	OK, but:
```
"error":"TypeError: group.toVersionString is not a function","stack":"
    at mapUserAgentProperties (/app/server/lib/amplitude.js:148:32)
    at mapBrowser (/app/server/lib/amplitude.js:135:10)
    at receiveEvent (/app/server/lib/amplitude.js:109:7)
    at events.forEach.event (/app/server/lib/flow-event.js:153:5)
    at Array.forEach (native)
    at module.exports (/app/server/lib/flow-event.js:119:10)
    at process.nextTick (/app/server/lib/routes/post-metrics.js:176:9)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by jrgm** [comment] 2018-04-30 22:39
I had a single instance of 110.3 in an ASG/ELB I could point my browser at and trigger the exception. I used `strace` and `tcpdump` to look at the node process and network at the time of the exception. I see **no** attempt to talk to Sentry and report the error.

**Comment by jrgm** [comment] 2018-04-30 22:41
Note also: sentry is network reachable by the content servers, and the configured DSN matches the value in Sentry.

**Comment by philbooth** [comment] 2018-05-01 06:51
Okay, this also explains why DataDog was affected, because `server/lib/statsd-collector.js` calls `toVersionString` too.

In hindsight I should have anticipated this in #6086 of course. And as was the case there, it's frustrating that I can't reproduce this locally.

Looking at the code, I almost wonder if prod has a different version of the `node-uap` dependency than we have locally. Locally I have @vladikoff's fork, which includes [this function](https://github.com/vladikoff/node-uap/blob/9cdd16247c8255d881820038d30db68b7926277d/index.js#L18-L23) that ensures the `toVersionString` function is created:

```js
// uap-ref-impl does not provide a `toVersionString` function. Add it.
function ensureToVersionString(context) {
  if (context && ! context.toVersionString) {
    context.toVersionString = toVersionString.bind(context);
  }
}

// ...cruft elided...

var _parse = refImpl.parse;
refImpl.parse = function (ua) {
  var result = _parse.call(refImpl, ua);

  // ua-parser results had a `toVersionString` function on `os` and `ua`.
  // Add the missing support.
  ensureToVersionString(result.os);
  ensureToVersionString(result.ua);

  return result;
};
```

@jrgm, is it possible that the `node-uap` dependency in prod is not resolved to Vlad's fork for some reason?

For instance, I notice that it also appears in shrinkwrap as a child dependency of `node-font-face-generator`, could that be interfering with our dependency on `git://github.com/vladikoff/node-uap.git#9cdd16247c8255d881820038d30db68b7926277d`?

**Comment by philbooth** [comment] 2018-05-01 06:53
> ... is it possible that the `node-uap` dependency in prod is not resolved to Vlad's fork for some reason?

e.g. maybe the switch to node 8/npm 5 has changed how are deps are resolved in a way that breaks this?

**Comment by philbooth** [comment] 2018-05-01 07:00
> I'm a bit surprised that Sentry didn't pick this up.

Presumably this is just because the error happens inside `process.nextTick`. Annoyingly Sentry *was* picking it up, or another instance of it, before I fixed it in #6086. And because I couldn't reproduce that error locally, I didn't pay much heed to it and didn't think about the other places it might be happening.

If we can get to the bottom of why it happens in prod and not locally, I'd be a lot more comfortable. The dependencies must be different somehow...

**Comment by shane-tomlinson** [comment] 2018-05-01 12:59
OK, so I've been able to get the wrong version of node-uap to install, one that does not contain `toVersionString`. I used npm@5 and node@6, but I have been unable to reproduce again. Here's a screenshot showing it *did* happen though:

<img width="735" alt="screen shot 2018-05-01 at 13 20 09" src="https://user-images.githubusercontent.com/848085/39473677-79e565ce-4d3f-11e8-8ca3-c15ab4cb9102.png">

**Comment by shane-tomlinson** [comment] 2018-05-01 13:01
The above message should say npm@{3|5}, I'm not sure which it was. :/

**Comment by shane-tomlinson** [comment] 2018-05-01 13:13
I pulled down the v1.110.5 dockerhub content-server image and saw this:

<img width="593" alt="screen shot 2018-05-01 at 14 07 33" src="https://user-images.githubusercontent.com/848085/39473953-1bb51984-4d41-11e8-8925-a2dd77a6b883.png">

node@6 and npm@3 being used.

Then, I looked at node_modules/node-uap/index.js and see this:

<img width="535" alt="screen shot 2018-05-01 at 14 11 32" src="https://user-images.githubusercontent.com/848085/39473968-321c368a-4d41-11e8-9c36-9126550bddbb.png">

npm@3 is incorrectly resolving node-uap and is not using @vladikoff's fixed version.

**Comment by shane-tomlinson** [comment] 2018-05-03 21:34
This has been fixed, closing.

**Closed by shane-tomlinson** 2018-05-03 21:34 UTC
Labels: waffle:review
