### ISSUE TITLE
Disconnected devices only appear disconnected in the device manager

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3970] opened 2016-07-25 15:12 UTC
On Thursday I disconnected every Firefox connected to my account, with the exception of the current device, in:
https://accounts.firefox.com/settings/devices?forceDeviceList=1

On Monday (today) all of the devices remain connected and function as normal. The only place that they no longer appear to be connected is in the device manager.

**Comment by rfk** [comment] 2016-07-26 03:09
To dig into this, I tried disconnecting one of my own devices, and here's some notes on the request:

* Correctly called `https://api.accounts.firefox.com/v1/account/device/destroy` with `{ "id": "57577925b1a252d5c61cf17433715376" }` in the request body
* Got a "200 OK" response
* It took a noticeably long time, approx five seconds with no visual feedback waiting for the server to disconnect the device:

![screen shot 2016-07-26 at 13 02 42](https://cloud.githubusercontent.com/assets/34695/17124837/54b54d82-5331-11e6-98aa-f1a8ec9836af.png)

We should escalate the apparent performance issue to a separate bug.

Anyway, since it appears to have made the correct call to the auth-server API, I wonder if there's a problem with the way `/devices/destroy` is actioning the request.  Will keep digging...

**Comment by rfk** [comment] 2016-07-26 03:45
FWIW I wasn't able to reproduce this on a fresh profile; steps I tried:

* Sign in to Firefox on my windows laptop
* Go to accounts.firefox.com on my mac, and view the devices list
* Disconnect the newly-added windows laptop
* Go back to the windows laptop and hit "sync now"

It correctly detected that it had been disconnected from sync, and prompted me to log in again.

@ryanfeeley do you still have the devices connected and functioning normally?  Do they continue to function normally after e.g. quitting Firefox and re-opening it?  I wonder if we're somehow busted the association between the device-id and the session-id for your devices, so that disconnect is not properly zapping the session token held by each device.

**Comment by rfk** [comment] 2016-08-01 02:09
(this is also why I'm keen to push forward on the "service dashboard" and related work - it shouldn't be possible for something to be connected to your account, but not show up anywhere in the management UI.  Broadening the scope of that view will help us fix that)

**Comment by vladikoff** [comment] 2016-08-23 18:13
Did some testing with this. 
This is broken in Stable, but fixed in Nightly.

When I press "Disconnect" in the clients (devices) view the Nighty browser is almost instantly logged out. Reopen if we need to do something about this in Stable (ff 48)

**Closed by vladikoff** 2016-08-23 18:13 UTC
Labels: waffle:active
