### ISSUE TITLE
Choose what to sync options clean-up

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3394] opened 2016-01-18 16:36 UTC
![choose](https://cloud.githubusercontent.com/assets/68213/12396767/34e3ac82-bdd7-11e5-9404-9cdb2a1a6ed6.gif)

1. Remove focus on first checkbox
1. Make checkbox labels less selectable
1. Make checkboxes align with copy (perhaps set the line-height of .fxa-checkbox__label to 20px?)
1. Add down-state depicted below
1. Watch Ryan squeal with glee. So thrilled to be launching this feature.
 
![checkbox](https://cloud.githubusercontent.com/assets/68213/12396780/44801c48-bdd7-11e5-9604-0de19e245045.png)

**Comment by philbooth** [comment] 2016-01-19 17:49
First input was focused in the fix for https://github.com/mozilla/fxa-content-server/issues/3339.

**Comment by vladikoff** [comment] 2016-01-19 17:49
note: watch out for small layouts, it collapses into 1 col

**Comment by vbudhram** [comment] 2016-01-26 00:21
@ryanfeeley The checkmark tick is a base encoded image https://github.com/mozilla/fxa-checkbox/blob/master/checkbox.scss#L21

Is it possible to generate the SVG with the correct color for the + down state?

**Comment by ryanfeeley** [comment] 2016-02-04 16:35
@vbudhram We can use filters for this too. Increase saturation by 40%, decrease brightness by 50%. I eyeballed it in Photoshop.

**Comment by ryanfeeley** [comment] 2016-04-26 20:08
@vladikoff @vbudhram Why was this one closed? Cleanup was not done AFIACT.

**Comment by rfk** [comment] 2016-04-26 20:29
I think this waffle may have closed this automatically when #3444 merged, but #3444 addressed some-but-not-all of the items highlighted here.  Let's take stock of current status of each:

> 1. Remove focus on first checkbox

The linked PR says we didn't do this because of #3342, need to revisit to find a way forward there.

> 2. Make checkbox labels less selectable

This is https://github.com/mozilla/fxa-checkbox/issues/7 and is still open

> 3. Make checkboxes align with copy (perhaps set the line-height of .fxa-checkbox__label to 20px?)

This appears to have been fixed in current release, @ryanfeeley can you confirm?

> 4. Add down-state depicted below

This is https://github.com/mozilla/fxa-content-server/issues/3691, right?

> 5. Watch Ryan squeal with glee. So thrilled to be launching this feature.

Oh man, I can't believe we missed doing this this part...

**Comment by rfk** [comment] 2016-04-26 20:34
>  > Remove focus on first checkbox
> The linked PR says we didn't do this because of #3342, need to revisit to find a way forward there.

So, #3342 says that we deliberately focus on the first input element in order to make the form submit when you press the "enter" key (#3339).  Is it possible to e.g. focus on the submit button directly rather than on a form element?

**Comment by philbooth** [comment] 2016-04-26 21:02
> Is it possible to e.g. focus on the submit button directly rather than on a form element?

It's definitely possible but it smells a bit funny to me from an accessibility point of view. People using a screen reader or just tabbing through with a keyboard would expect to tab forwards through the form imho, not backwards to reach it if they want to change a selection.

**Comment by rfk** [comment] 2016-04-27 00:12
Maybe we can use `tabindex` to make the submit button first in tab order, so that hitting tab moves focus from there onto the first checkbox.  I dunno, I'm kinda out of my frontend depth at that point...

**Comment by philbooth** [comment] 2016-04-27 08:05
> Maybe we can use `tabindex` to make the submit button first in tab order, so that hitting tab moves focus from there onto the first checkbox. I dunno, I'm kinda out of my frontend depth at that point...

I could accept that. But also, if the problem is a visual one (I'm assuming it is), is there not a styling change we could make?

**Comment by shane-tomlinson** [comment] 2016-04-27 10:33
> Maybe we can use tabindex to make the submit button first in tab order, so that hitting tab moves focus from there onto the first checkbox. I dunno, I'm kinda out of my frontend depth at that point...

That too would break keyboard user expectations. @ryanfeeley - why the desire to remove focus, aesthetics? We could experiment with focusing the form element, which might satisfy all parties.

**Comment by rfk** [comment] 2016-04-27 21:36
>  why the desire to remove focus

It's surprisingly easy to accidentally uncheck the first item ("Tabs") when interacting with the form.  IIRC there was a user in one of @ryanfeeley's usertesting videos who did this without realizing it and was confused that their tabs weren't syncing.  I did it as well when stepping through the flow to follow up on it.

**Comment by vladikoff** [comment] 2016-04-28 16:34
from mtg: probably focus submit, @ryanfeeley concerns?

**Comment by vbudhram** [comment] 2016-05-09 03:28
@ryanfeeley quick update on this PR, a few more items got merged in for it. The only outstanding item is reducing the checkbox select size.

1. Remove focus on first checkbox (merged https://github.com/mozilla/fxa-content-server/issues/3703)
2. Make checkbox labels less selectable (WIP https://github.com/mozilla/fxa-checkbox/issues/7)
3. Make checkboxes align with copy (merged)
4. Add down-state depicted below (merged https://github.com/mozilla/fxa-checkbox/issues/9)

**Comment by vbudhram** [comment] 2016-05-31 14:01
@ryanfeeley, the last remaining items for this have been merged. Possible to verify that I didn't miss anything before closing? https://latest.dev.lcip.org Thanks!

**Comment by vladikoff** [comment] 2016-05-31 21:36
@ryanfeeley says "Great."

**Closed by vladikoff** 2016-05-31 21:36 UTC
Labels: waffle:active

**Comment by TDA** [comment] 2016-06-01 05:39
`Watch Ryan squeal with glee. So thrilled to be launching this feature.`
Did this happen? Did anyone capture this on camera?
