### ISSUE TITLE
strange partial circle when profile image is not found.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2117] opened 2015-02-19 13:17 UTC
My profile server in fxa-local-dev is not working correctly, so profile images are not being stored/retrieved correctly. All uploaded profile images 404, leaving a strange partial circle on the screen:

![screen shot 2015-02-19 at 13 16 05](https://cloud.githubusercontent.com/assets/848085/6267171/aece1dec-b839-11e4-8c05-7f10678d81af.png)

Link to #2116

**Comment by ckarlof** [comment] 2015-02-19 15:43
I've seen this too.

**Comment by zaach** [comment] 2015-02-19 16:07
Dupe of #1804.

**Closed by zaach** 2015-02-19 16:07 UTC
Labels: avatars, backlog
