### ISSUE TITLE
flaky tests on latest

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3058] opened 2015-09-13 18:32 UTC
I stole	some time to run 9 consecutive tests on	latest,	when nothing else was changing. Here are the failures:

   2/9 firefox on any platform - oauth reset password - reset password, verify same browser
   2/9 firefox on any platform - oauth web channel - password reset, verify same browser
   2/9 firefox on any platform - oauth web channel keys - password reset, verify same browser
   2/9 firefox on any platform - reset_password flow - verifying a reset password unlocks an account
   1/9 firefox on any platform - Firefox Desktop Sync reset password - sync reset password, verify same browser
   1/9 firefox on any platform - oauth web channel keys - signup, verify same browser, in a different tab, with original tab open

**Comment by rfk** [comment] 2015-09-14 04:39
Prioritizing this all the way into `waffle:now`; IIUC this is behind the TeamCity test failures we've been seeing recently.

**Comment by rfk** [comment] 2015-09-14 06:55
Possible dupe of #2483?

**Comment by vladikoff** [comment] 2015-09-15 16:02
> verify same browser

Yeah looking at all those tests, all failing due to issues detailed in #2483

**Closed by vladikoff** 2015-09-15 16:02 UTC
Labels: waffle:now
