### ISSUE TITLE
[Unblock sign-in] Authorization code is required even if the password is correct

### ISSUE THREAD

**Issue by petruta** [mozilla/fxa-content-server#4280] opened 2016-10-14 09:19 UTC
[Steps to reproduce]:
1. Go to https://signin-unblock.dev.lcip.org/
2. Enter the email address and the password for an account already created

[Expected result]:
Account's settings page is opened

[Actual result]:
"Authorize this sign-in" page is opened

**Comment by shane-tomlinson** [comment] 2016-10-14 10:08
@petruta - can you explain more?

**Comment by petruta** [comment] 2016-10-14 10:31
The authorization code should only be requested when entering the wrong password.
All my attempts with an @mailinator,com account require the authorization code even if the password I entered is correct.

**Comment by shane-tomlinson** [comment] 2016-10-14 10:53
@petruta - Thanks for the response, there are two things at play here.

First, rate limiting occurs before the password is checked to prevent brute force attacks on a single account. If rate limiting only occurred after the password was checked, it would allow an attacker to keep guessing passwords using a botnet until they correctly guessed the password.

Second, on that box, I have forced *all* mailinator signin requests to be blocked so that I could show off the feature internally. When merged to latest, it'll be `block.*@restmail.net` to facilitate automated testing.

**Comment by shane-tomlinson** [comment] 2016-10-20 14:46
Thanks again for the report @petruta. I do not believe there is anything actionable here since the rate limiting is by design, even if the password is correct.

**Closed by shane-tomlinson** 2016-10-20 14:46 UTC
