### ISSUE TITLE
mozilla.org/en-US/firefox/accounts iframe loading is not consistent

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3518] opened 2016-02-18 19:21 UTC
## STR

Open https://www.mozilla.org/en-US/firefox/accounts/
iframe shows up
resize the browser
CMD+R to refresh
iframe does not load 

![ref](https://cloud.githubusercontent.com/assets/128755/13155243/d98c4862-d64a-11e5-9dae-56dfe511518b.gif)

Details: if devtools is open the iframe always loads.

**Comment by miketaylr** [comment] 2016-02-18 19:34
![iframe](https://cloud.githubusercontent.com/assets/67283/13155626/2ec26ae8-d644-11e5-8072-ecf36c5c5c52.gif)

Yeah, can reproduce in stable here:

STR:
1) Load https://www.mozilla.org/en-US/firefox/accounts/
2) Reload page.

Expected: can see the iframe?
Actual: every other time the iframe is blocked. :hankey:

**Comment by pdehaan** [comment] 2016-02-18 19:37
50% of the time it works 100% of the time!

**Comment by vladikoff** [comment] 2016-02-18 19:45
The iframe always shows in Chrome with Firefox's user agent.

Side issue in Chrome though (with Firefox's user agent, **not sure if related to this**), if you sign up via accounts.firefox.com and reload the https://www.mozilla.org/en-US/firefox/accounts/ page then the iframe will disappear:



![chrome-ref](https://cloud.githubusercontent.com/assets/128755/13155879/e7c5b15e-d64d-11e5-8eca-2a756a809262.gif)

**Comment by philbooth** [comment] 2016-02-23 14:41
At first I couldn't reproduce this issue at all. Then I enabled e10s and was able to reproduce it reliably.

Doing some further investigation with e10s turned off again, I can reproduce it if I right-click inside the iframe and choose `This Frame > Reload Frame`. But f I reload the whole page when e10s is disabled, it doesn't happen.

**Comment by shane-tomlinson** [comment] 2016-02-23 17:02
> Then I enabled e10s and was able to reproduce it reliably.

*e10s*....  sigh.

**Comment by rfk** [comment] 2016-02-23 21:40
I get a console error log about X-Frame-Options:

```
Load denied by X-Frame-Options: https://accounts.firefox.com/signup?utm_campaign=fxa-embedded-form&utm_medium=referral&utm_source=accounts-page&utm_content=fx-&entrypoint=accounts-page&service=sync&context=iframe&style=chromeless&haltAfterSignIn=true does not permit framing.
```

**Comment by rfk** [comment] 2016-02-23 21:44
> I can reproduce it if I right-click inside the iframe and choose This Frame > Reload Frame

This I can explain as follows:

* On initial load, the iframe requests "/", which allows iframing via X-Frame-Options.
* The iframe renders and navigates itself to "/signin"
* Reloading the frame requests "/signin" which sends "X-Frame-Options: DENY"

**Comment by rfk** [comment] 2016-02-23 21:57
Interestingly, I *still* see the X-Frame-Options message logged to the console when I do the reload-the-page-with-e10s-on-and-devtools-closed method:

```
Load denied by X-Frame-Options: https://accounts.firefox.com/signup?utm_campaign=fxa-embedded-form&utm_medium=referral&utm_source=accounts-page&utm_content=fx-&entrypoint=accounts-page&service=sync&context=fx_firstrun_v2&style=chromeless&haltAfterSignIn=true does not permit framing.
```

**Comment by rfk** [comment] 2016-02-23 22:08
(Actually I appear to be able to repro this in both release and nightly, with or without e10s)

**Comment by philbooth** [comment] 2016-02-24 06:39
How many origins are we legitimately iframeable from? Is it feasible to change [our usage of `helmet.xframe`](https://github.com/mozilla/fxa-content-server/blob/master/server/bin/fxa-content-server.js#L67) to something like the following?

```js
    app.use(helmet.xframe('allow-from', 'https://www.mozilla.org'));
```

**Comment by rfk** [comment] 2016-02-24 06:43
several unfortunately, ref https://github.com/mozilla/fxa-content-server/issues/3473

**Comment by philbooth** [comment] 2016-02-24 11:37
In that case, what if we replaced the call to `helmet.xframe` with our own middleware, which checks the request origin against a list of approved iframers? Then depending on whether there is a match, we can set the `X-Frame-Options` header on the response appropriately.

Good idea or bad idea? @shane-tomlinson? @vladikoff?

**Comment by philbooth** [comment] 2016-02-24 11:43
(actually, that's a massive assumption on my part about the request origin, testing whether it works that way now)

**Comment by philbooth** [comment] 2016-02-24 13:25
(okay, ignore me, the origin isn't set on the iframe request)

**Comment by rfk** [comment] 2016-02-24 20:24
@shane-tomlinson suggested a staged approach to fixing this in conversation yesterday, assigning to him for further clarification

**Comment by shane-tomlinson** [comment] 2016-02-29 16:06
For now, let's just allow `/signin` and `/signup` to be framed, using the same rules we currently have. This doesn't fully fix the problem, but should be "better". 

A more robust fix is to use `x-frame-options` and CSP headers and ditch the postMessage dance.

1. Have any flows that iframe us send a new query parameter, `origin`. 
1. Compare the `origin` against a list of origins allowed to frame the content server. If `service=sync`, this will be a list that probably comes from configuration. For OAuth reliers, we look up the OAuth client info.
1. Serve both x-frame-options and the new [CSP frame-ancestors](https://w3c.github.io/webappsec-csp/document/#directive-frame-ancestors) directive.
1. Let the browser handle the rest.

We'll have to ensure this still works for about:accounts which uses an iframe in a privileged context.

**Closed** 2016-02-29 20:30 UTC
Labels: waffle:review
