### ISSUE TITLE
Settings: Communication preferences can end up in an odd state

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-content-server#5198] opened 2017-06-30 18:38 UTC
If a user clicks on the communications preferences checkbox rapidly, the state can become out of sync with what we think it is on the server.

**Comment by philbooth** [comment] 2017-07-25 16:31
@ryanfeeley, Shane mentioned that you originally designed this checkbox to have a spinner overlay while the request is in flight to the back-end, so that user's don't send racing subscribe/unsubscribe attempts. Is that still the preferred approach for handling this?

**Comment by vladikoff** [comment] 2017-07-25 18:18
@philbooth we used mdl lite as the base for the checkbox, this might be helpful for you to add a loading state: https://getmdl.io/components/index.html#loading-section/spinner

**Comment by philbooth** [comment] 2017-07-26 07:52
Actually, I misunderstood this issue, I don't think it's to do with clicking rapidly as much as it is to do with clicking more than twice.

If I click slowly three times with a 5-second pause in between, checked => wait => unchecked => wait => checked, when I subsequently view my communication preferences in `/settings` it doesn't think I'm subscribed.

**Comment by philbooth** [comment] 2017-07-26 08:22
The content server uses `this.$('.marketing-email-optin').is(':checked')` to determine whether the user has checked the checkbox. For me at least, the `checked` attribute is never set, only the parent `label` element gets an `is-checked` attribute.

Looking at the source for `fxa-checkbox`, it seems like that is by design. The content-server's expectation about the `checked` attribute doesn't seem unreasonable though, so I'm leaning towards updating `fxa-checkbox` rather than making the content server check the parent.

**Comment by philbooth** [comment] 2017-07-26 09:47
> For me at least, the `checked` attribute is never set, only the parent `label` element gets an `is-checked` attribute.

As usual I was talking rubbish here. `this.$('.marketing-email-optin').is(':checked')` works correctly, that's not the issue.

**Comment by philbooth** [comment] 2017-07-26 11:00
I don't understand what this problem actually is, I realise. There were a couple of things I thought it was, related to me running locally and also general stupidity, but testing against prod I can't reproduce anything like the described behaviour. Anyone else know / can reproduce?

/cc @seanmonstar

**Comment by seanmonstar** [comment] 2017-07-26 17:14
I don't know, I just wrote what was said during the triage at the all-hands! @shane-tomlinson I think reported this, he probably knows best?

**Comment by shane-tomlinson** [comment] 2017-07-31 14:25
I haven't been able to reproduce this, closing.

**Closed by shane-tomlinson** 2017-07-31 14:25 UTC
Labels: waffle:active
